import assert from "node:assert/strict";
import {createInitialState,evaluateResponse,submitAttempt,shouldAdvance,computeSimulationStatus,computeCriticalFailureRecord,computeCompetencyStatus} from "../logic.js";
import {STAGES,DECISIONS,DECISION_ORDER,COMPETENCY_LABELS} from "../content.js";
let passed=0,failed=0;function t(n,f){try{f();passed++;console.log(`PASS  ${n}`)}catch(e){failed++;console.log(`FAIL  ${n}\n      ${e.message}`)}}
t("continuous ten-stage case",()=>assert.equal(STAGES.length,10));
t("22 meaningful decisions",()=>assert.equal(DECISION_ORDER.length,22));
t("all 14 competency families used",()=>{const u=new Set(DECISION_ORDER.map(id=>DECISIONS[id].competency));assert.equal(Object.keys(COMPETENCY_LABELS).length,14);for(let n=1;n<=14;n++)assert.ok(u.has(`C${String(n).padStart(2,"0")}`));});
t("six controlling critical families only",()=>{const f=new Set(DECISION_ORDER.map(id=>DECISIONS[id].criticalFailureFamily).filter(Boolean));assert.deepEqual([...f].sort(),["CF1_ACT_ON_PAYMENT_REDIRECTION","CF2_ENTITY_AS_CONTACT_PROOF","CF3_PROCEED_THROUGH_CONTACT_CONTRADICTION","CF4_PROCEED_WITH_INACTIVE_AUTHORITY","CF5_UNSUPPORTED_FRAUD_CONCLUSION","CF6_BYPASS_MATERIAL_MISMATCH"]);});
t("entity does not authenticate contact",()=>{assert.equal(evaluateResponse("SIM06-D04","B"),true);assert.equal(evaluateResponse("SIM06-D04","A"),false);});
t("trusted callback must be independent",()=>{assert.equal(evaluateResponse("SIM06-D06","B"),true);assert.equal(evaluateResponse("SIM06-D06","A"),false);});
t("document check flags actual mismatches only",()=>{assert.equal(evaluateResponse("SIM06-D08",["legalName","mc","pickupRef"]),true);assert.equal(evaluateResponse("SIM06-D08",["legalName","mc","pickupRef","rate"]),false);});
t("inactive authority blocks booking",()=>{assert.equal(evaluateResponse("SIM06-D11","B"),true);assert.equal(evaluateResponse("SIM06-D11","A"),false);});
t("duplicate posting is ambiguity not proof",()=>{assert.equal(evaluateResponse("SIM06-D12","B"),true);assert.equal(evaluateResponse("SIM06-D12","A"),false);});
t("payment redirection is critical",()=>{let s=createInitialState();s=submitAttempt(s,"SIM06-D14","A",1000);assert.equal(s.decisions["SIM06-D14"].criticalFailureOccurred,true);});
t("urgency does not lower standard",()=>{assert.equal(evaluateResponse("SIM06-D16","A"),true);assert.equal(evaluateResponse("SIM06-D16","B"),false);});
t("later evidence keeps buckets separate",()=>assert.equal(evaluateResponse("SIM06-D18",{entity:"verified",contact:"contradicted",document:"contradicted",payment:"contradicted",duplicate:"unresolved"}),true));
t("critical failure survives same-item correction",()=>{let s=createInitialState();s=submitAttempt(s,"SIM06-D04","A",1000);s=submitAttempt(s,"SIM06-D04","B",2000);assert.equal(s.decisions["SIM06-D04"].finalCorrect,true);assert.equal(s.decisions["SIM06-D04"].criticalFailureOccurred,true);assert.equal(s.decisions["SIM06-D04"].instructorReviewRequired,true);assert.equal(computeSimulationStatus(s),"INSTRUCTOR_REVIEW_REQUIRED");});
t("critical wrong answer advances diagnostically but cannot pass",()=>{let s=createInitialState();s=submitAttempt(s,"SIM06-D11","A",1000);assert.equal(shouldAdvance(s,"SIM06-D11"),true);assert.equal(computeSimulationStatus(s),"INSTRUCTOR_REVIEW_REQUIRED");});
t("critical record preserves first attempt",()=>{let s=createInitialState();s=submitAttempt(s,"SIM06-D14","A",1111);assert.deepEqual(computeCriticalFailureRecord(s),[{decisionId:"SIM06-D14",family:"CF1_ACT_ON_PAYMENT_REDIRECTION",firstAttemptResponse:"A",firstAttemptTimestamp:1111}]);});
t("competency status exposes instructor review",()=>{let s=createInitialState();s=submitAttempt(s,"SIM06-D13","A",1000);assert.equal(computeCompetencyStatus(s).C08,"Needs Instructor Review");});
console.log(`\n${passed} passed, ${failed} failed`);if(failed)process.exit(1);
