// Run with: node tests/logic.test.js
import assert from "node:assert/strict";
import {createInitialState,evaluateResponse,submitAttempt,submitReassessment,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeFinalMasteryScore,computeCompetencyStatus,computeCriticalFailureStatus,getStageForDecision,getProgress,normalizeLoadedState} from "../logic.js";
import {DECISION_ORDER,DECISIONS,STAGES} from "../content.js";
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log(`PASS  ${name}`)}catch(e){failed++;console.log(`FAIL  ${name}`);console.log(`      ${e.message}`)}}
test("content: seven stages in order",()=>{assert.equal(STAGES.length,7);assert.deepEqual(STAGES.map(s=>s.id),["SIM02-S1","SIM02-S2","SIM02-S3","SIM02-S4","SIM02-S5","SIM02-S6","SIM02-S7"])});
test("content: fifteen stable SIM02 decision IDs",()=>{assert.equal(DECISION_ORDER.length,15);for(const id of DECISION_ORDER)assert.match(id,/^SIM02-D\d\d$/)});
test("content: every stage decision resolves",()=>{for(const s of STAGES)for(const id of s.decisionIds)assert.ok(DECISIONS[id])});
test("evaluateResponse choice",()=>{assert.equal(evaluateResponse("SIM02-D01","B"),true);assert.equal(evaluateResponse("SIM02-D01","A"),false)});
test("evaluateResponse multiselect order independent",()=>{assert.equal(evaluateResponse("SIM02-D02",["equipment","relationship"]),true);assert.equal(evaluateResponse("SIM02-D02",["relationship"]),false)});
test("evaluateResponse eight-stage sequence",()=>assert.equal(evaluateResponse("SIM02-D15",["stop","identify","trace","check","classify","act","document","escalate"]),true));
test("first attempt immutable",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D01","A",1);s=submitAttempt(s,"SIM02-D01","B",2);assert.equal(s.decisions["SIM02-D01"].firstAttemptResponse,"A");assert.equal(s.decisions["SIM02-D01"].finalResponse,"B")});
test("ordinary wrong answer requires retry",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D01","A",1);assert.equal(shouldAdvance(s,"SIM02-D01"),false)});
test("exactly three high-stakes decisions",()=>assert.deepEqual(DECISION_ORDER.filter(id=>DECISIONS[id].escalateAfterAttempts),["SIM02-D06","SIM02-D10","SIM02-D13"]));
test("critical trigger persists after same-screen correction",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D06","A",1);s=submitAttempt(s,"SIM02-D06","B",2);s=submitAttempt(s,"SIM02-D06","C",3);assert.equal(s.decisions["SIM02-D06"].instructorReviewRequired,true);assert.equal(computeCriticalFailureStatus(s)["M02-CF-01"],"REASSESSMENT_REQUIRED")});
test("alternate reassessment resolves without erasing trigger",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D06","A",1);s=submitAttempt(s,"SIM02-D06","B",2);s=submitAttempt(s,"SIM02-D06","C",3);s=submitReassessment(s,"M02-CF-01","B",4);assert.equal(s.criticalFailures["M02-CF-01"].occurred,true);assert.equal(computeCriticalFailureStatus(s)["M02-CF-01"],"RESOLVED_BY_REASSESSMENT")});
test("simulation status requires review while critical unresolved",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D10","B",1);s=submitAttempt(s,"SIM02-D10","C",2);assert.equal(computeSimulationStatus(s),"INSTRUCTOR_REVIEW_REQUIRED")});
test("full mastery without critical trigger completes",()=>{let s=createInitialState();const c={"SIM02-D01":"B","SIM02-D02":["relationship","equipment"],"SIM02-D03":"A","SIM02-D04":["oneOffer","noChoice"],"SIM02-D05":"B","SIM02-D06":"C","SIM02-D07":["shipperDirect","chooseCarrier"],"SIM02-D08":"B","SIM02-D09":"A","SIM02-D10":"A","SIM02-D11":["allocation","compReason"],"SIM02-D12":"B","SIM02-D13":"B","SIM02-D14":"C","SIM02-D15":["stop","identify","trace","check","classify","act","document","escalate"]};for(const[id,r]of Object.entries(c))s=submitAttempt(s,id,r,1);assert.equal(computeSimulationStatus(s),"COMPLETE");assert.deepEqual(computeFinalMasteryScore(s),{correct:15,total:15})});
test("competency status mastered and remediated",()=>{let a=createInitialState();a=submitAttempt(a,"SIM02-D01","B",1);assert.equal(computeCompetencyStatus(a).A,"Mastered");let b=createInitialState();b=submitAttempt(b,"SIM02-D01","A",1);b=submitAttempt(b,"SIM02-D01","B",2);assert.equal(computeCompetencyStatus(b).A,"Mastered After Remediation")});
test("normalization preserves shape and rejects foreign state",()=>{let s=createInitialState();s=submitAttempt(s,"SIM02-D01","B",1);assert.equal(normalizeLoadedState(s).decisions["SIM02-D01"].finalCorrect,true);assert.equal(normalizeLoadedState({simulationId:"SIM-001",decisions:{}}).simulationId,"SIM-002")});
test("normalization backfills premium critical controls",()=>{const n=normalizeLoadedState({simulationId:"SIM-002",decisions:{"SIM02-D01":{finalCorrect:true}},currentDecisionId:"SIM02-D01"});assert.equal(Object.keys(n.criticalFailures).length,3);assert.ok(Array.isArray(n.reassessmentHistory))});
test("progression and helpers stable",()=>{assert.equal(getStageForDecision("SIM02-D06").id,"SIM02-S3");assert.deepEqual(getProgress("SIM02-D15"),{current:15,total:15});assert.equal(getNextDecisionId("SIM02-D15"),null)});
test("D09 rejects non-overlap safe harbor",()=>assert.match(`${DECISIONS["SIM02-D09"].correctFeedback} ${DECISIONS["SIM02-D09"].remediation}`,/not an automatic legal safe harbor/i));
console.log("");console.log(`${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
