// SIM-003 content data module.
// Isolated from SIM-001 and SIM-002 (no shared imports) — guarantees zero regression risk
// to either approved runtime. Structurally similar to both by design so a future shared
// engine extraction (justified once a third/fourth simulation confirms real duplication)
// would be a mechanical merge, not a rewrite.
//
// Source of truth for wording: 02-CURRICULUM/Module-03/ (all parts), 03-ASSESSMENTS/
// Practical-Assessments/Module-03-Practical.md, 03-ASSESSMENTS/Instructor-Answer-Guides/
// Module-03.md, 04-STUDENT-TOOLS/Module-03-Tools/ (Load Fit Verification Checklist,
// STOP/VERIFY/ESCALATE Decision Tool, Weight & Dimension Verification Worksheet).

export const STAGES = [
  { id: "SIM03-S1", title: "Equipment File", decisionIds: ["SIM03-D01", "SIM03-D02"] },
  { id: "SIM03-S2", title: "Standard Dry-Van Load", decisionIds: ["SIM03-D03", "SIM03-D04"] },
  { id: "SIM03-S3", title: "Temperature-Control Conflict", decisionIds: ["SIM03-D05", "SIM03-D06"] },
  { id: "SIM03-S4", title: "Overwidth / Specialized Load", decisionIds: ["SIM03-D07", "SIM03-D08"] },
  { id: "SIM03-S5", title: "Driver / Endorsement Event", decisionIds: ["SIM03-D09", "SIM03-D10"] },
  { id: "SIM03-S6", title: "Weight / Axle Trap", decisionIds: ["SIM03-D11", "SIM03-D12"] },
  { id: "SIM03-S7", title: "Incomplete Load File", decisionIds: ["SIM03-D13", "SIM03-D14", "SIM03-D15"] },
];

export const ARTIFACTS = {
  equipmentProfile: {
    title: "Equipment Profile",
    lines: [
      "Trailer: 53-foot dry van",
      "Width configuration: 102-inch legal-width (National Network figure)",
      "Temperature control: none — non-temperature-controlled",
      "Driver: ordinary dry-van experience",
      "Driver endorsements: no H or X hazardous-materials endorsement on file",
    ],
  },
  loadTenderA: {
    title: "Load Tender A",
    lines: [
      "Commodity: packaged home goods",
      "Weight: 31,000 lb",
      "Width: 96 inches",
      "Loading method: standard dock loading",
      "Temperature control required: no",
      "Special handling: none stated",
    ],
  },
  loadTenderB: {
    title: "Load Tender B",
    lines: [
      "Commodity: frozen food",
      "Temperature requirement: continuous -10\u00b0F",
      "Equipment requested: refrigerated trailer",
    ],
  },
  loadTenderC: {
    title: "Load Tender C — Oversize Information Request",
    lines: [
      "Commodity: rigid industrial machinery",
      "Width: 104 inches",
      "Permit information: not yet provided",
      "Route/state information: not yet provided",
    ],
  },
  loadTenderD: {
    title: "Load Tender D",
    lines: [
      "Commodity: placarded hazardous material",
      "Required qualification: H or X endorsement",
      "Assigned driver: the driver on file in the Equipment Profile (no H or X endorsement)",
    ],
  },
  weightProjectionE: {
    title: "Weight Projection Sheet",
    lines: [
      "Projected gross combination weight: 79,400 lb",
    ],
  },
  axleDistributionE: {
    title: "Axle Distribution Sheet",
    lines: [
      "Drive tandem: 35,000 lb",
    ],
  },
  shipperLoadNoteF: {
    title: "Shipper Load Note",
    lines: [
      "\"53-foot van, 44,500 lb.\"",
      "No further detail provided.",
    ],
  },
};

export const COMPETENCY_LABELS = {
  A: "Equipment identification",
  B: "Commodity/equipment compatibility",
  C: "Temperature-control compatibility",
  D: "Dimension/overwidth issue spotting",
  E: "Driver endorsement compatibility",
  F: "Gross-vs-axle weight reasoning",
  G: "Missing-information/verification discipline",
  H: "Operational proceed/reject/escalate decision",
  I: "Multi-factor load-fit reasoning",
};

export const DECISIONS = {
  "SIM03-D01": {
    id: "SIM03-D01",
    stageId: "SIM03-S1",
    type: "multiselect",
    competency: "A",
    artifact: "equipmentProfile",
    prompt: "Select every fact about this equipment/driver that is currently KNOWN from the file. (Select all that apply.)",
    options: [
      { key: "trailerType", text: "The trailer is a 53-foot dry van" },
      { key: "widthConfig", text: "The trailer's width configuration is the 102-inch legal-width figure" },
      { key: "noTempControl", text: "The trailer has no temperature-control capability" },
      { key: "driverNoHX", text: "The driver holds no H or X endorsement" },
      { key: "actualInteriorDims", text: "This specific trailer's actual usable interior dimensions" },
      { key: "actualTareWeight", text: "This specific tractor-trailer's actual current tare weight" },
    ],
    correctSet: ["trailerType", "widthConfig", "noTempControl", "driverNoHX"],
    correctFeedback: "Correct. The equipment type, width configuration, lack of temperature control, and the driver's endorsement gap are all stated directly. Actual usable interior dimensions and actual current tare weight are not given here — a nominal \"53-foot dry van\" label is a starting point, not a guarantee of exact figures.",
    remediation: "Only select what this file actually states. A '53-foot dry van' label does not by itself tell you this specific trailer's exact usable interior dimensions or current tare weight — those still require verification when a real load is being evaluated.",
  },
  "SIM03-D02": {
    id: "SIM03-D02",
    stageId: "SIM03-S1",
    type: "multiselect",
    competency: "G",
    prompt: "Which of these will still need to be verified on a load-by-load basis before you can confirm fit, even with this equipment profile in hand? (Select all that apply.)",
    options: [
      { key: "commodityFit", text: "Whether a given commodity is compatible with this equipment" },
      { key: "dimensionFit", text: "Whether given freight dimensions fit this trailer" },
      { key: "weightAxle", text: "Whether given weight and axle distribution are legal for this combination" },
      { key: "companyName", text: "The name of the trucking company (already known)" },
    ],
    correctSet: ["commodityFit", "dimensionFit", "weightAxle"],
    correctFeedback: "Correct. Commodity compatibility, dimension fit, and weight/axle legality all depend on the specific load being offered — none of them are settled just by having this equipment profile on file.",
    remediation: "The company name is already known and doesn't need re-verification. Commodity, dimension, and weight/axle fit are all load-specific questions this equipment profile alone cannot answer.",
  },
  "SIM03-D03": {
    id: "SIM03-D03",
    stageId: "SIM03-S2",
    type: "choice",
    competency: "B",
    artifact: "loadTenderA",
    prompt: "Based on the equipment profile and this load tender, how should Load A be classified?",
    choices: [
      { key: "A", text: "GOOD FIT on the facts supplied" },
      { key: "B", text: "BAD FIT" },
      { key: "C", text: "SPECIALIZED / ESCALATE" },
      { key: "D", text: "NEEDS MORE INFORMATION" },
    ],
    correctKey: "A",
    correctFeedback: "GOOD FIT on the facts supplied. Commodity, weight, width, and loading method all match a standard dry-van dock-loaded shipment, with no temperature or special-handling conflict.",
    remediation: "Compare each fact against the equipment profile: dry van, no temperature control needed, 96 inches (within the 102-inch legal-width configuration), standard dock loading, no special handling. Nothing here conflicts with the available equipment.",
  },
  "SIM03-D04": {
    id: "SIM03-D04",
    stageId: "SIM03-S2",
    type: "multiselect",
    competency: "B",
    prompt: "Select the fact(s) that support classifying Load A as a good fit. (Select all that apply.)",
    options: [
      { key: "widthOk", text: "96 inches is within the 102-inch legal-width configuration" },
      { key: "noTempNeeded", text: "No temperature control is required, and the equipment has none to conflict with" },
      { key: "standardLoading", text: "Standard dock loading matches ordinary dry-van loading capability" },
      { key: "weightAlone", text: "31,000 lb is under 80,000 lb" },
    ],
    correctSet: ["widthOk", "noTempNeeded", "standardLoading"],
    correctFeedback: "Correct. Weight alone being under 80,000 lb is true but isn't, by itself, what makes this a good fit — width, temperature, and loading compatibility are what actually confirm it here.",
    remediation: "Being under 80,000 lb is necessary but not sufficient reasoning — see Stage 6 for why gross weight alone never confirms fit. Focus on the width, temperature, and loading-method matches instead.",
  },
  "SIM03-D05": {
    id: "SIM03-D05",
    stageId: "SIM03-S3",
    type: "choice",
    competency: "C",
    artifact: "loadTenderB",
    prompt: "How should Load B be classified for the equipment on file?",
    choices: [
      { key: "A", text: "GOOD FIT — dry vans can generally handle any commodity" },
      { key: "B", text: "BAD FIT — the equipment has no temperature-control capability" },
      { key: "C", text: "SPECIALIZED / ESCALATE" },
      { key: "D", text: "NEEDS MORE INFORMATION" },
    ],
    correctKey: "B",
    correctFeedback: "BAD FIT. A dry van has no active temperature-control unit. Frozen food requiring continuous -10\u00b0F cannot move on this equipment — this is a straightforward equipment-type mismatch, not a situation to try to \"make work.\"",
    remediation: "Dry van does not equal reefer capability. A non-temperature-controlled trailer cannot satisfy a continuous-temperature requirement, regardless of how the load otherwise looks.",
  },
  "SIM03-D06": {
    id: "SIM03-D06",
    stageId: "SIM03-S3",
    type: "choice",
    competency: "C",
    prompt: "What is the correct operational response to Load B?",
    choices: [
      { key: "A", text: "Try to insulate or work around the temperature issue with the dry van" },
      { key: "B", text: "Reject this load for this equipment — it requires equipment this carrier does not have" },
      { key: "C", text: "Accept and note the risk to the shipper afterward" },
      { key: "D", text: "Ask the driver to keep the trailer doors closed to maintain temperature" },
    ],
    correctKey: "B",
    correctFeedback: "Reject the load for this equipment. A genuine equipment-type mismatch (no temperature control unit at all) is not something to work around operationally — the correct response is to decline for this equipment.",
    remediation: "None of the workaround options actually solve a missing temperature-control unit. When the equipment fundamentally lacks the required capability, the correct response is to reject the load for this equipment, not attempt an operational fix.",
  },
  "SIM03-D07": {
    id: "SIM03-D07",
    stageId: "SIM03-S4",
    type: "choice",
    competency: "D",
    artifact: "loadTenderC",
    prompt: "This load is 104 inches wide against the 102-inch legal-width configuration on file. How should it be classified?",
    choices: [
      { key: "A", text: "BAD FIT — automatically illegal because it exceeds 102 inches" },
      { key: "B", text: "GOOD FIT — a permit will automatically be available" },
      { key: "C", text: "SPECIALIZED / ESCALATE — verify state/route/permit/equipment requirements before proceeding" },
      { key: "D", text: "GOOD FIT — 2 inches over is close enough to ignore" },
    ],
    correctKey: "C",
    correctFeedback: "SPECIALIZED / ESCALATE. Exceeding 102 inches does not automatically make a load illegal, and it does not automatically mean a permit is available either. Verify state/jurisdiction, route, permit process, and equipment before concluding either way.",
    remediation: "Both 'automatically illegal' and 'automatically fine with a permit' are wrong. Overwidth freight requires verification of the specific states, routes, and permit process involved — it isn't resolved by the width figure alone in either direction.",
  },
  "SIM03-D08": {
    id: "SIM03-D08",
    stageId: "SIM03-S4",
    type: "multiselect",
    competency: "D",
    prompt: "What must be verified before Load C can be classified with confidence? (Select all that apply.)",
    options: [
      { key: "statesRoutes", text: "Which states and routes are involved" },
      { key: "permitProcess", text: "Whether those jurisdictions permit this specific overwidth condition, and the permit process/lead time" },
      { key: "equipmentReady", text: "Whether the carrier's equipment and driver are set up for oversize movement" },
      { key: "colorOfTruck", text: "The color of the tractor" },
    ],
    correctSet: ["statesRoutes", "permitProcess", "equipmentReady"],
    correctFeedback: "Correct. State/route, permit process, and equipment/driver readiness for oversize movement are all genuinely relevant. Irrelevant cosmetic details aren't part of the verification.",
    remediation: "Focus on what's operationally and legally relevant: states/routes, permit process, and oversize-movement readiness. Irrelevant details don't belong in this verification.",
  },
  "SIM03-D09": {
    id: "SIM03-D09",
    stageId: "SIM03-S5",
    type: "choice",
    competency: "E",
    artifact: "loadTenderD",
    prompt: "The assigned driver holds no H or X endorsement. How should Load D be classified?",
    choices: [
      { key: "A", text: "GOOD FIT — the driver can take the load and get certified later" },
      { key: "B", text: "NEEDS MORE INFORMATION — check the exact hazard class first" },
      { key: "C", text: "BAD FIT / DO NOT DISPATCH — the driver lacks the required qualification for this specific load" },
      { key: "D", text: "SPECIALIZED / ESCALATE — assign a different trailer instead" },
    ],
    correctKey: "C",
    correctFeedback: "BAD FIT / DO NOT DISPATCH. A required hazmat endorsement is a hard driver-qualification requirement, not something to work around, defer, or solve with different equipment. This driver cannot be dispatched on this specific load.",
    remediation: "This is a critical safety/legal issue, not a scheduling inconvenience. A driver lacking a required endorsement cannot be dispatched on a load that requires it — there is no acceptable workaround here.",
    escalateAfterAttempts: 2,
  },
  "SIM03-D10": {
    id: "SIM03-D10",
    stageId: "SIM03-S5",
    type: "choice",
    competency: "E",
    prompt: "Which statement correctly distinguishes the H, N, and X endorsements?",
    choices: [
      { key: "A", text: "H and X mean exactly the same thing" },
      { key: "B", text: "H covers hazardous materials generally; N covers tank vehicles; X is the combined tank-vehicle-plus-hazmat qualification — a driver with only H does not satisfy a load requiring X" },
      { key: "C", text: "N is required for all placarded loads" },
      { key: "D", text: "X is only relevant for interstate loads" },
    ],
    correctKey: "B",
    correctFeedback: "Correct. H, N, and X are three distinct qualifications. X specifically requires both the tank-vehicle (N) and hazardous-materials (H) elements together — holding H alone does not satisfy an X requirement.",
    remediation: "Review the distinction: H is hazardous materials generally, N is tank vehicles, and X is the combined requirement for a placarded hazmat load in a tank vehicle. They are not interchangeable.",
  },
  "SIM03-D11": {
    id: "SIM03-D11",
    stageId: "SIM03-S6",
    type: "choice",
    competency: "F",
    artifact: "weightProjectionE",
    prompt: "Gross combination weight projects at 79,400 lb — under the 80,000 lb federal baseline. How should Load E be classified once you also check the axle distribution sheet?",
    choices: [
      { key: "A", text: "GOOD FIT — 79,400 lb is under 80,000 lb, so it's legal" },
      { key: "B", text: "BAD FIT / DO NOT DISPATCH as stated — the drive tandem is independently over its own legal limit, regardless of the legal gross total" },
      { key: "C", text: "NEEDS MORE INFORMATION — gross weight alone isn't enough detail" },
      { key: "D", text: "GOOD FIT — axle distribution doesn't matter if gross weight is legal" },
    ],
    correctKey: "B",
    correctFeedback: "BAD FIT / DO NOT DISPATCH as stated. The drive tandem carries 35,000 lb — over the federal 34,000 lb tandem-axle limit — independently of the fact that gross combination weight is under 80,000 lb. Gross-weight legality and axle-group legality are two separate checks, and this load fails the second one.",
    remediation: "Under 80,000 lb gross does not cure an independently excessive axle group. Check the axle distribution sheet: 35,000 lb on the drive tandem exceeds the 34,000 lb federal limit for that axle group, regardless of the legal gross total.",
    escalateAfterAttempts: 2,
  },
  "SIM03-D12": {
    id: "SIM03-D12",
    stageId: "SIM03-S6",
    type: "multiselect",
    competency: "F",
    artifact: "axleDistributionE",
    prompt: "Why doesn't the legal gross weight (79,400 lb) resolve the axle-distribution problem? (Select all that apply.)",
    options: [
      { key: "separateChecks", text: "Gross-weight legality and axle-group legality are two independent checks, and both must pass" },
      { key: "tandemLimit", text: "The federal tandem-axle limit (34,000 lb) applies to that specific axle group regardless of the gross total" },
      { key: "grossIsCargo", text: "80,000 lb represents cargo weight alone, so it doesn't apply here" },
      { key: "underThreshold", text: "Being under any federal threshold automatically clears every other check" },
    ],
    correctSet: ["separateChecks", "tandemLimit"],
    correctFeedback: "Correct. The 80,000 lb figure is a gross combination baseline (not cargo weight alone), and passing it does not automatically clear the independent tandem-axle limit.",
    remediation: "80,000 lb is the gross combination weight baseline, not cargo weight alone — and no single threshold check ever automatically clears every other requirement. Axle-group limits are independent checks.",
  },
  "SIM03-D13": {
    id: "SIM03-D13",
    stageId: "SIM03-S7",
    type: "multiselect",
    competency: "G",
    artifact: "shipperLoadNoteF",
    prompt: "\"53-foot van, 44,500 lb\" is all the shipper has provided. Select every category of information that is still missing. (Select all that apply.)",
    options: [
      { key: "tareWeight", text: "Actual tractor-trailer tare weight" },
      { key: "axleDistribution", text: "Axle/load distribution" },
      { key: "commodity", text: "Commodity" },
      { key: "dimensions", text: "Dimensions" },
      { key: "loadingMethod", text: "Loading method / facility requirements" },
      { key: "trailerLength", text: "Trailer length (already stated: 53 feet)" },
    ],
    correctSet: ["tareWeight", "axleDistribution", "commodity", "dimensions", "loadingMethod"],
    correctFeedback: "Correct. Trailer length is the one thing actually given. Everything else — tare weight, axle distribution, commodity, dimensions, and loading/facility details — is genuinely missing and needed before this load can be classified.",
    remediation: "Trailer length (53 feet) is already stated — don't mark it missing. But weight and length alone never tell you tare weight, axle distribution, commodity, dimensions, or loading requirements. All of those are still unknown here.",
  },
  "SIM03-D14": {
    id: "SIM03-D14",
    stageId: "SIM03-S7",
    type: "choice",
    competency: "H",
    prompt: "Given everything still missing, how should Load F be classified right now?",
    choices: [
      { key: "A", text: "GOOD FIT — a 53-foot van can generally handle 44,500 lb" },
      { key: "B", text: "BAD FIT — reject outright" },
      { key: "C", text: "NEEDS MORE INFORMATION — do not assume fit or reject until the missing categories are verified" },
      { key: "D", text: "SPECIALIZED / ESCALATE" },
    ],
    correctKey: "C",
    correctFeedback: "NEEDS MORE INFORMATION. With commodity, dimensions, tare weight, axle distribution, and loading requirements all unknown, there isn't enough information to classify this load as either a good or bad fit yet.",
    remediation: "A trailer-length-and-weight statement alone never proves fit. Don't default to assuming it's fine, and don't reject it outright either — the correct classification when this much is missing is NEEDS MORE INFORMATION.",
  },
  "SIM03-D15": {
    id: "SIM03-D15",
    stageId: "SIM03-S7",
    type: "sequencing",
    competency: "I",
    prompt: "Put the correct response steps in order for handling Load F's missing information.",
    items: [
      { key: "stop", text: "STOP — do not classify the load as fit or unfit yet" },
      { key: "identify", text: "IDENTIFY exactly which categories of information are missing" },
      { key: "verify", text: "VERIFY the missing information through the shipper or an appropriate source" },
      { key: "donotassume", text: "DO NOT ASSUME any missing fact based on trailer length or weight alone" },
    ],
    correctOrder: ["stop", "identify", "verify", "donotassume"],
    correctFeedback: "STOP first, so you don't classify prematurely. Then IDENTIFY the specific missing categories. Then VERIFY them through an appropriate source. Throughout, DO NOT ASSUME any of them from the limited facts given — this discipline applies across every stage of this simulation, not just Load F.",
    remediation: "The order matters: stop before classifying, then identify the specific gaps, then verify them — and never assume a missing fact just because one related fact (like trailer length) happens to be known.",
  },
};

export const DECISION_ORDER = STAGES.flatMap((s) => s.decisionIds);
