import {DECISIONS,DECISION_ORDER,STAGES} from "./content.js";
import {CRITICAL_FAMILIES,DECISION_TO_CRITICAL_FAMILY,REASSESSMENTS} from "./critical-controls.js";
function freshDecision(){return {firstAttemptResponse:null,firstAttemptCorrect:null,firstAttemptTimestamp:null,finalResponse:null,finalCorrect:null,remediationUsed:false,attemptCount:0,finalTimestamp:null,instructorReviewRequired:false,criticalFailureOccurred:false,criticalFailureFamily:null,criticalFailureTriggeredAt:null,criticalFailureResolved:false}}
function freshCritical(){const o={};for(const f of Object.keys(CRITICAL_FAMILIES))o[f]={occurred:false,decisionId:CRITICAL_FAMILIES[f].decisionId,triggeredAt:null,resolved:false,reassessment:null};return o}
export function createInitialState(){const decisions={};for(const id of DECISION_ORDER)decisions[id]=freshDecision();return {simulationId:"SIM-003",currentDecisionId:DECISION_ORDER[0],decisions,criticalFailures:freshCritical(),reassessmentHistory:[],status:"IN_PROGRESS",startedAt:null,completedAt:null}}
function seteq(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length)return false;const x=new Set(a),y=new Set(b);if(x.size!==y.size)return false;for(const v of x)if(!y.has(v))return false;return true}
export function evaluateResponse(id,r){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);if(d.type==="choice")return r===d.correctKey;if(d.type==="matching")return !!r&&typeof r==="object"&&d.items.every(i=>r[i]===d.correctMap[i]);if(d.type==="sequencing")return Array.isArray(r)&&r.length===d.correctOrder.length&&d.correctOrder.every((k,i)=>r[i]===k);if(d.type==="multiselect")return seteq(r,d.correctSet);throw new Error(`Unknown decision type: ${d.type}`)}
export function submitAttempt(state,id,response,now=Date.now()){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);const record={...state.decisions[id]},correct=evaluateResponse(id,response);if(record.firstAttemptResponse===null){record.firstAttemptResponse=response;record.firstAttemptCorrect=correct;record.firstAttemptTimestamp=now}else record.remediationUsed=true;record.attemptCount++;record.finalResponse=response;record.finalCorrect=correct;record.finalTimestamp=now;let criticalFailures={...state.criticalFailures};const family=DECISION_TO_CRITICAL_FAMILY[id];if(!correct&&d.escalateAfterAttempts&&record.attemptCount>=d.escalateAfterAttempts){record.instructorReviewRequired=true;record.criticalFailureOccurred=true;record.criticalFailureFamily=family;record.criticalFailureTriggeredAt=record.criticalFailureTriggeredAt??now;record.criticalFailureResolved=false;criticalFailures={...criticalFailures,[family]:{...criticalFailures[family],occurred:true,triggeredAt:criticalFailures[family]?.triggeredAt??now,resolved:false}}}else if(correct&&record.criticalFailureOccurred)record.instructorReviewRequired=!record.criticalFailureResolved;else if(correct)record.instructorReviewRequired=false;return {...state,decisions:{...state.decisions,[id]:record},criticalFailures}}
export function submitReassessment(state,family,response,now=Date.now()){const r=REASSESSMENTS[family],existing=state.criticalFailures?.[family];if(!r)throw new Error(`Unknown critical family: ${family}`);if(!existing?.occurred)throw new Error(`Critical family not triggered: ${family}`);const correct=response===r.correctKey,a={family,response,correct,timestamp:now,scenario:r.scenario},criticalFailures={...state.criticalFailures,[family]:{...existing,resolved:correct,reassessment:a}},id=CRITICAL_FAMILIES[family].decisionId,decision={...state.decisions[id],criticalFailureResolved:correct,instructorReviewRequired:!correct};return {...state,criticalFailures,decisions:{...state.decisions,[id]:decision},reassessmentHistory:[...(state.reassessmentHistory||[]),a]}}
export function computeCriticalFailureStatus(state){const o={};for(const f of Object.keys(CRITICAL_FAMILIES)){const r=state.criticalFailures?.[f];o[f]=!r?.occurred?"NOT_TRIGGERED":r.resolved?"RESOLVED_BY_REASSESSMENT":"REASSESSMENT_REQUIRED"}return o}
export function shouldAdvance(s,id){const r=s.decisions[id];return r.finalCorrect===true||r.instructorReviewRequired===true}export function getNextDecisionId(id){const i=DECISION_ORDER.indexOf(id);return i<0||i===DECISION_ORDER.length-1?null:DECISION_ORDER[i+1]}
export function computeSimulationStatus(s){const unresolved=Object.values(computeCriticalFailureStatus(s)).some(v=>v==="REASSESSMENT_REQUIRED");if(unresolved)return "INSTRUCTOR_REVIEW_REQUIRED";return DECISION_ORDER.every(id=>s.decisions[id].finalCorrect===true)?"COMPLETE":"IN_PROGRESS"}
export function computeFirstAttemptScore(s){return {correct:DECISION_ORDER.filter(id=>s.decisions[id].firstAttemptCorrect===true).length,total:15}}export function computeFinalMasteryScore(s){return {correct:DECISION_ORDER.filter(id=>s.decisions[id].finalCorrect===true).length,total:15}}export function computeRemediationCount(s){return DECISION_ORDER.filter(id=>s.decisions[id].remediationUsed).length}
export function computeCompetencyStatus(s){const by={};for(const id of DECISION_ORDER)(by[DECISIONS[id].competency]||=[]).push(id);const o={};for(const[c,ids]of Object.entries(by)){const rs=ids.map(id=>s.decisions[id]);if(rs.some(r=>r.instructorReviewRequired))o[c]="Needs Instructor Review";else if(rs.some(r=>r.finalCorrect===null))o[c]="In Progress";else if(rs.every(r=>r.finalCorrect===true&&!r.remediationUsed))o[c]="Mastered";else if(rs.every(r=>r.finalCorrect===true))o[c]="Mastered After Remediation";else o[c]="In Progress"}return o}
export function computeCompletionRecord(s){return {simulationId:"SIM-003",firstAttemptScore:computeFirstAttemptScore(s),finalMasteryScore:computeFinalMasteryScore(s),remediationCount:computeRemediationCount(s),competencies:computeCompetencyStatus(s),criticalFailures:s.criticalFailures||freshCritical(),reassessmentHistory:s.reassessmentHistory||[],instructorReviewState:computeSimulationStatus(s)==="INSTRUCTOR_REVIEW_REQUIRED"?"REQUIRED":"CLEAR",finalStatus:computeSimulationStatus(s)}}
export function getStageForDecision(id){return STAGES.find(x=>x.id===DECISIONS[id].stageId)||null}export function getProgress(id){return {current:DECISION_ORDER.indexOf(id)+1,total:15}}
export function normalizeLoadedState(raw){if(!raw||typeof raw!=="object"||raw.simulationId!=="SIM-003"||!raw.decisions||typeof raw.decisions!=="object")return createInitialState();const f=createInitialState(),decisions={};for(const id of DECISION_ORDER)decisions[id]=raw.decisions[id]&&typeof raw.decisions[id]==="object"?{...f.decisions[id],...raw.decisions[id]}:f.decisions[id];const criticalFailures={...f.criticalFailures};for(const family of Object.keys(criticalFailures))if(raw.criticalFailures?.[family])criticalFailures[family]={...criticalFailures[family],...raw.criticalFailures[family]};return {...f,...raw,decisions,criticalFailures,reassessmentHistory:Array.isArray(raw.reassessmentHistory)?raw.reassessmentHistory:[],currentDecisionId:DECISION_ORDER.includes(raw.currentDecisionId)?raw.currentDecisionId:DECISION_ORDER[0]}}
