import {DECISIONS,STAGES,ARTIFACTS,COMPETENCY_LABELS} from "./content.js";
import {CRITICAL_FAMILIES,REASSESSMENTS} from "./critical-controls.js";
import {createInitialState,submitAttempt,submitReassessment,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeFirstAttemptScore,computeFinalMasteryScore,computeRemediationCount,computeCompetencyStatus,computeCriticalFailureStatus,getStageForDecision,getProgress,normalizeLoadedState} from "./logic.js";
const STORAGE_KEY="sim002-state-v1";function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeLoadedState(JSON.parse(r)):null}catch{return null}}function save(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
let state=load()||createInitialState(),pending=null,feedback=false,reassessmentFeedback=null;const root=document.getElementById("app");
function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==="class")n.className=v;else if(k.startsWith("on")&&typeof v==="function")n.addEventListener(k.slice(2),v);else n.setAttribute(k,v)}for(const c of [].concat(children)){if(c==null)continue;n.appendChild(typeof c==="string"?document.createTextNode(c):c)}return n}
function artifact(key){const a=ARTIFACTS[key];if(!a)return null;return el("section",{class:"artifact-card","aria-label":a.title},[el("div",{class:"artifact-title"},a.title),...a.lines.map(x=>el("p",{},x||" "))])}
function choice(d){const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.choices){const id=`c-${d.id}-${o.key}`,i=el("input",{type:"radio",name:d.id,id,value:o.key,onchange:()=>pending=o.key});if(pending===o.key)i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},o.key),el("span",{},o.text)]))}return f}
function multi(d){if(!Array.isArray(pending))pending=[];const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.options){const id=`m-${d.id}-${o.key}`,i=el("input",{type:"checkbox",id,value:o.key,onchange:e=>{const s=new Set(pending);e.target.checked?s.add(o.key):s.delete(o.key);pending=[...s]}});if(pending.includes(o.key))i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{},o.text)]))}return f}
function sequence(d){if(!Array.isArray(pending))pending=d.items.map(x=>x.key).slice().reverse();const list=el("ol",{class:"sequence-list"});pending.forEach((key,index)=>{const item=d.items.find(x=>x.key===key);list.appendChild(el("li",{class:"sequence-item"},[el("span",{},item.text),el("button",{type:"button",onclick:()=>{if(index){const a=pending.slice();[a[index-1],a[index]]=[a[index],a[index-1]];pending=a;render()}}},"↑ Up"),el("button",{type:"button",onclick:()=>{if(index<pending.length-1){const a=pending.slice();[a[index+1],a[index]]=[a[index],a[index+1]];pending=a;render()}}},"↓ Down")]))});return list}
function control(d){return d.type==="choice"?choice(d):d.type==="multiselect"?multi(d):sequence(d)}function complete(d){return d.type==="choice"?typeof pending==="string":Array.isArray(pending)&&pending.length>0}
function progress(id){const p=getProgress(id),s=getStageForDecision(id),si=STAGES.findIndex(x=>x.id===s.id)+1;return el("div",{class:"progress-bar",role:"status"},`Stage ${si} of ${STAGES.length}: ${s.title} — Decision ${p.current} of ${p.total}`)}
function decision(id){const d=DECISIONS[id],r=state.decisions[id],box=el("div",{class:"decision-screen"},[progress(id)]);if(d.artifact)box.appendChild(artifact(d.artifact));box.appendChild(el("h2",{},d.prompt));if(!feedback){box.appendChild(control(d));box.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitAttempt(state,id,pending,Date.now());save(state);feedback=true;render()}},"Submit"));return box}box.appendChild(el("div",{class:`feedback-panel ${r.finalCorrect?"feedback-correct":"feedback-incorrect"}`},[el("p",{},r.finalCorrect?d.correctFeedback:d.remediation),...(r.instructorReviewRequired?[el("p",{class:"feedback-escalation"},"This high-stakes family is preserved in the record. Correcting this screen can improve final mastery, but an alternate fact-pattern reassessment is required before the family is cleared.")]:[]),el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(shouldAdvance(state,id)){const next=getNextDecisionId(id);pending=null;feedback=false;if(next)state={...state,currentDecisionId:next};else state={...state,status:computeSimulationStatus(state),completedAt:Date.now()};save(state);render()}else{pending=null;feedback=false;render()}}},shouldAdvance(state,id)?"Continue":"Try again")]));return box}
function unresolved(){const s=computeCriticalFailureStatus(state);return Object.keys(s).filter(k=>s[k]==="REASSESSMENT_REQUIRED")}
function reassess(){const family=unresolved()[0],r=REASSESSMENTS[family],meta=CRITICAL_FAMILIES[family],box=el("div",{class:"decision-screen"},[el("h1",{},"Alternate High-Stakes Reassessment"),el("p",{},`${family} — ${meta.label}`),el("section",{class:"artifact-card"},[el("div",{class:"artifact-title"},"New fact pattern"),el("p",{},r.scenario)]),el("h2",{},r.prompt)]);if(reassessmentFeedback!==null){box.appendChild(el("div",{class:`feedback-panel ${reassessmentFeedback?"feedback-correct":"feedback-incorrect"}`},[el("p",{},reassessmentFeedback?"Reassessment passed. The original trigger remains in history and is marked resolved by alternate reassessment.":"Reassessment not yet passed. Apply the controlling principle to this new fact pattern."),el("button",{type:"button",class:"btn btn-primary",onclick:()=>{reassessmentFeedback=null;pending=null;state={...state,status:computeSimulationStatus(state)};save(state);render()}},reassessmentFeedback?"Continue":"Try again") ]));return box}const f=el("fieldset",{class:"choice-group"});for(const[k,text]of Object.entries(r.choices)){const id=`r-${family}-${k}`,i=el("input",{type:"radio",name:`r-${family}`,id,value:k,onchange:()=>pending=k});f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},k),el("span",{},text)]))}box.appendChild(f);box.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(typeof pending!=="string")return;const ok=pending===r.correctKey;state=submitReassessment(state,family,pending,Date.now());state={...state,status:computeSimulationStatus(state)};save(state);pending=null;reassessmentFeedback=ok;render()}},"Submit reassessment"));return box}
function start(){return el("div",{class:"start-screen"},[el("h1",{},"Module 02 — Agency Boundary Desk"),el("p",{},"Seven-stage carrier-side agency and brokerage-risk decision simulation."),el("button",{type:"button",class:"btn btn-primary",onclick:()=>{state={...state,startedAt:state.startedAt||Date.now()};save(state);render()}},state.startedAt?"Resume Simulation":"Start Simulation")])}
function done(){if(unresolved().length)return reassess();const f=computeFirstAttemptScore(state),m=computeFinalMasteryScore(state),r=computeRemediationCount(state),cs=computeCompetencyStatus(state),box=el("div",{class:"completion-screen"},[el("h1",{},"Simulation Complete"),el("p",{},`First attempt ${f.correct}/${f.total}; final mastery ${m.correct}/${m.total}; remediation used on ${r} decision(s).`)]);const list=el("div",{class:"competency-summary"},[el("h2",{},"Competency Summary")]);for(const[k,label]of Object.entries(COMPETENCY_LABELS))list.appendChild(el("div",{class:"competency-row"},[el("span",{},label),el("span",{},cs[k]||"In Progress")]));box.appendChild(list);box.appendChild(el("p",{},"Browser storage is local demonstration persistence only; durable LMS/student records remain release-layer work."));return box}
function reset(){return el("button",{type:"button",class:"btn btn-text",onclick:()=>{if(!confirm("Reset this browser's SIM-002 history?"))return;state=createInitialState();pending=null;feedback=false;reassessmentFeedback=null;save(state);render()}},"Reset simulation")}
function render(){root.innerHTML="";root.appendChild(el("header",{class:"app-header"},[el("div",{class:"app-title"},"Elite Dispatcher Academy — SIM-002"),reset()]));root.appendChild(el("main",{},!state.startedAt?start():(state.status==="COMPLETE"||state.status==="INSTRUCTOR_REVIEW_REQUIRED")?done():decision(state.currentDecisionId)))}render();
