import { DECISIONS, DECISION_ORDER, STAGES } from "./content.js";
import { CRITICAL_FAMILIES, DECISION_TO_CRITICAL_FAMILY, REASSESSMENTS } from "./critical-controls.js";

function freshDecision(){return {firstAttemptResponse:null,firstAttemptCorrect:null,firstAttemptTimestamp:null,finalResponse:null,finalCorrect:null,remediationUsed:false,attemptCount:0,finalTimestamp:null,instructorReviewRequired:false,criticalFailureOccurred:false,criticalFailureFamily:null,criticalFailureTriggeredAt:null,criticalFailureResolved:false};}
function freshCritical(){const out={};for(const family of Object.keys(CRITICAL_FAMILIES))out[family]={occurred:false,decisionId:CRITICAL_FAMILIES[family].decisionId,triggeredAt:null,resolved:false,reassessment:null};return out;}
export function createInitialState(){const decisions={};for(const id of DECISION_ORDER)decisions[id]=freshDecision();return {simulationId:"SIM-002",currentDecisionId:DECISION_ORDER[0],decisions,criticalFailures:freshCritical(),reassessmentHistory:[],status:"IN_PROGRESS",startedAt:null,completedAt:null};}
function arraysEqualAsSets(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length)return false;const sa=new Set(a),sb=new Set(b);if(sa.size!==sb.size)return false;for(const v of sa)if(!sb.has(v))return false;return true;}
export function evaluateResponse(id,response){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);if(d.type==="choice")return response===d.correctKey;if(d.type==="matching")return !!response&&typeof response==="object"&&d.items.every(item=>response[item]===d.correctMap[item]);if(d.type==="sequencing")return Array.isArray(response)&&response.length===d.correctOrder.length&&d.correctOrder.every((key,i)=>response[i]===key);if(d.type==="multiselect")return arraysEqualAsSets(response,d.correctSet);throw new Error(`Unknown decision type: ${d.type}`);}
export function submitAttempt(state,id,response,now=Date.now()){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);const record={...state.decisions[id]},correct=evaluateResponse(id,response);if(record.firstAttemptResponse===null){record.firstAttemptResponse=response;record.firstAttemptCorrect=correct;record.firstAttemptTimestamp=now}else record.remediationUsed=true;record.attemptCount+=1;record.finalResponse=response;record.finalCorrect=correct;record.finalTimestamp=now;let criticalFailures={...state.criticalFailures};const family=DECISION_TO_CRITICAL_FAMILY[id];if(!correct&&d.escalateAfterAttempts&&record.attemptCount>=d.escalateAfterAttempts){record.instructorReviewRequired=true;record.criticalFailureOccurred=true;record.criticalFailureFamily=family;record.criticalFailureTriggeredAt=record.criticalFailureTriggeredAt??now;record.criticalFailureResolved=false;criticalFailures={...criticalFailures,[family]:{...criticalFailures[family],occurred:true,triggeredAt:criticalFailures[family]?.triggeredAt??now,resolved:false}}}else if(correct&&record.criticalFailureOccurred){record.instructorReviewRequired=!record.criticalFailureResolved;}else if(correct){record.instructorReviewRequired=false;}return {...state,decisions:{...state.decisions,[id]:record},criticalFailures};}
export function submitReassessment(state,family,response,now=Date.now()){const r=REASSESSMENTS[family];if(!r)throw new Error(`Unknown critical family: ${family}`);const existing=state.criticalFailures?.[family];if(!existing?.occurred)throw new Error(`Critical family not triggered: ${family}`);const correct=response===r.correctKey;const assessment={family,response,correct,timestamp:now,scenario:r.scenario};const criticalFailures={...state.criticalFailures,[family]:{...existing,resolved:correct,reassessment:assessment}};const decisionId=CRITICAL_FAMILIES[family].decisionId,decision={...state.decisions[decisionId],criticalFailureResolved:correct,instructorReviewRequired:!correct};return {...state,criticalFailures,decisions:{...state.decisions,[decisionId]:decision},reassessmentHistory:[...(state.reassessmentHistory||[]),assessment]};}
export function computeCriticalFailureStatus(state){const out={};for(const family of Object.keys(CRITICAL_FAMILIES)){const r=state.criticalFailures?.[family];out[family]=!r?.occurred?"NOT_TRIGGERED":r.resolved?"RESOLVED_BY_REASSESSMENT":"REASSESSMENT_REQUIRED";}return out;}
export function shouldAdvance(state,id){const r=state.decisions[id];return r.finalCorrect===true||r.instructorReviewRequired===true;}
export function getNextDecisionId(id){const i=DECISION_ORDER.indexOf(id);return i===-1||i===DECISION_ORDER.length-1?null:DECISION_ORDER[i+1];}
export function computeSimulationStatus(state){const allFinalCorrect=DECISION_ORDER.every(id=>state.decisions[id].finalCorrect===true);const unresolved=Object.values(computeCriticalFailureStatus(state)).some(v=>v==="REASSESSMENT_REQUIRED");if(unresolved)return "INSTRUCTOR_REVIEW_REQUIRED";return allFinalCorrect?"COMPLETE":"IN_PROGRESS";}
export function computeFirstAttemptScore(state){return {correct:DECISION_ORDER.filter(id=>state.decisions[id].firstAttemptCorrect===true).length,total:DECISION_ORDER.length};}
export function computeFinalMasteryScore(state){return {correct:DECISION_ORDER.filter(id=>state.decisions[id].finalCorrect===true).length,total:DECISION_ORDER.length};}
export function computeRemediationCount(state){return DECISION_ORDER.filter(id=>state.decisions[id].remediationUsed).length;}
export function computeCompetencyStatus(state){const by={};for(const id of DECISION_ORDER)(by[DECISIONS[id].competency]||=[]).push(id);const result={};for(const [c,ids] of Object.entries(by)){const rs=ids.map(id=>state.decisions[id]);if(rs.some(r=>r.instructorReviewRequired)){result[c]="Needs Instructor Review";continue}if(rs.some(r=>r.finalCorrect===null)){result[c]="In Progress";continue}if(rs.every(r=>r.finalCorrect===true&&!r.remediationUsed)){result[c]="Mastered";continue}if(rs.every(r=>r.finalCorrect===true)){result[c]="Mastered After Remediation";continue}result[c]="In Progress";}return result;}
export function computeCompletionRecord(state){return {simulationId:"SIM-002",firstAttemptScore:computeFirstAttemptScore(state),finalMasteryScore:computeFinalMasteryScore(state),remediationCount:computeRemediationCount(state),competencies:computeCompetencyStatus(state),criticalFailures:state.criticalFailures||freshCritical(),reassessmentHistory:state.reassessmentHistory||[],instructorReviewState:computeSimulationStatus(state)==="INSTRUCTOR_REVIEW_REQUIRED"?"REQUIRED":"CLEAR",finalStatus:computeSimulationStatus(state)};}
export function getStageForDecision(id){return STAGES.find(s=>s.id===DECISIONS[id].stageId)||null;}
export function getProgress(id){return {current:DECISION_ORDER.indexOf(id)+1,total:DECISION_ORDER.length};}
export function normalizeLoadedState(raw){if(!raw||typeof raw!=="object"||raw.simulationId!=="SIM-002"||!raw.decisions||typeof raw.decisions!=="object")return createInitialState();const fresh=createInitialState(),decisions={};for(const id of DECISION_ORDER)decisions[id]=raw.decisions[id]&&typeof raw.decisions[id]==="object"?{...fresh.decisions[id],...raw.decisions[id]}:fresh.decisions[id];const criticalFailures={...fresh.criticalFailures};for(const family of Object.keys(criticalFailures))if(raw.criticalFailures?.[family])criticalFailures[family]={...criticalFailures[family],...raw.criticalFailures[family]};return {...fresh,...raw,decisions,criticalFailures,reassessmentHistory:Array.isArray(raw.reassessmentHistory)?raw.reassessmentHistory:[],currentDecisionId:DECISION_ORDER.includes(raw.currentDecisionId)?raw.currentDecisionId:DECISION_ORDER[0]};}
