import {DECISIONS,STAGES,ARTIFACTS,COMPETENCY_LABELS,REASSESSMENTS,CRITICAL_FAILURE_FAMILIES} from "./content.js";
import {createInitialState,submitAttempt,submitCriticalReassessment,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeCompletionRecord,getNextUnresolvedCriticalFamily,getStageForDecision,getProgress,normalizeLoadedState} from "./logic.js";

const STORAGE_KEY="sim008-premium-state-v2";
function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeLoadedState(JSON.parse(r)):null}catch{return null}}
function save(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
let state=load()||createInitialState(),pending=null,feedback=false;
const root=document.getElementById("app");

function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==="class")n.className=v;else if(k.startsWith("on")&&typeof v==="function")n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}for(const c of [].concat(children)){if(c==null)continue;n.appendChild(typeof c==="string"?document.createTextNode(c):c)}return n;}
function artifact(key){const a=ARTIFACTS[key];if(!a)return null;const box=el("section",{class:"artifact-card","aria-label":a.title},[el("div",{class:"artifact-title"},a.title)]);for(const line of a.lines)box.appendChild(el("p",{},line));return box;}
function choice(d){const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.choices){const id=`c-${d.id}-${o.key}`,i=el("input",{type:"radio",name:d.id,id,value:o.key,onchange:()=>pending=o.key});if(pending===o.key)i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},o.key),el("span",{},o.text)]));}return f;}
function multi(d){if(!Array.isArray(pending))pending=[];const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.options){const id=`m-${d.id}-${o.key}`,i=el("input",{type:"checkbox",id,value:o.key,onchange:e=>{const s=new Set(pending);e.target.checked?s.add(o.key):s.delete(o.key);pending=[...s];}});if(pending.includes(o.key))i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{},o.text)]));}return f;}
function categorize(d){if(!pending||typeof pending!=="object"||Array.isArray(pending))pending={};const wrap=el("div",{class:"categorize-group"});for(const item of d.items){const row=el("fieldset",{class:"categorize-row"},[el("legend",{class:"categorize-item-text"},item.text)]);for(const b of d.buckets){const id=`cat-${d.id}-${item.key}-${b.key}`,i=el("input",{type:"radio",name:`cat-${d.id}-${item.key}`,id,value:b.key,onchange:()=>pending={...pending,[item.key]:b.key}});if(pending[item.key]===b.key)i.checked=true;row.appendChild(el("label",{for:id,class:"choice-option categorize-bucket-option"},[i,el("span",{},b.label)]));}wrap.appendChild(row);}return wrap;}
function control(d){if(d.type==="choice")return choice(d);if(d.type==="categorize")return categorize(d);return multi(d);}
function complete(d){if(d.type==="choice")return typeof pending==="string";if(d.type==="categorize")return pending&&typeof pending==="object"&&!Array.isArray(pending)&&d.items.every(i=>pending[i.key]);return Array.isArray(pending)&&pending.length>0;}
function progress(id){const p=getProgress(id),s=getStageForDecision(id),si=STAGES.findIndex(x=>x.id===s.id)+1;return el("div",{class:"progress-bar",role:"status"},[el("div",{class:"progress-text"},`Stage ${si} of ${STAGES.length}: ${s.title} — Decision ${p.current} of ${p.total}`),el("div",{class:"progress-track"},[el("div",{class:"progress-fill",style:`width:${p.current/p.total*100}%`} )])]);}

function advanceFrom(id){const next=getNextDecisionId(id);pending=null;feedback=false;if(next){state={...state,currentDecisionId:next};}else{state={...state,status:computeSimulationStatus(state)};}save(state);render();}
function feedbackPanel(id){const d=DECISIONS[id],r=state.decisions[id],ok=r.finalCorrect,p=el("div",{class:`feedback-panel ${ok?"feedback-correct":"feedback-incorrect"}`,role:"alert"},[el("p",{class:"feedback-heading"},ok?"Correct":"Review required"),el("p",{},ok?d.correctFeedback:d.remediation)]);if(r.criticalFailureOccurred&&!r.criticalFailureResolved)p.appendChild(el("p",{class:"feedback-escalation"},`Critical-failure evidence preserved: ${r.criticalFailureFamily}. Correcting this screen does not erase it. A materially different reassessment will be required after the scenario.`));const advance=shouldAdvance(state,id);p.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>advance?advanceFrom(id):(feedback=false,pending=null,render())},advance?"Continue":"Try again"));return p;}
function decision(id){const d=DECISIONS[id],c=el("div",{class:"decision-screen"},[progress(id)]);if(d.artifact)c.appendChild(artifact(d.artifact));c.appendChild(el("h2",{class:"decision-prompt"},d.prompt));if(!feedback){c.appendChild(control(d));c.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitAttempt(state,id,pending,Date.now());save(state);feedback=true;render();}},"Submit"));}else c.appendChild(feedbackPanel(id));return c;}

function reassessmentScreen(family){const d=REASSESSMENTS[family],rr=state.reassessments[family],box=el("div",{class:"decision-screen"},[el("h1",{},"Critical Reassessment"),el("p",{},`${family}: ${CRITICAL_FAILURE_FAMILIES[family]}`),el("p",{},"This is a materially different fact pattern. Your original first-attempt evidence remains in the record.")]);if(d.artifact)box.appendChild(artifact(d.artifact));box.appendChild(el("h2",{class:"decision-prompt"},d.prompt));box.appendChild(control(d));box.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitCriticalReassessment(state,family,pending,Date.now());pending=null;save(state);const updated=state.reassessments[family];if(!updated.resolved){feedback=false;render();return;}const next=getNextUnresolvedCriticalFamily(state);if(!next)state={...state,status:computeSimulationStatus(state),completedAt:Date.now()};save(state);render();}},rr?.attemptCount?"Submit Reassessment Again":"Submit Reassessment"));if(rr?.attemptCount&&!rr.resolved)box.appendChild(el("p",{class:"feedback-escalation"},"Reassessment not yet demonstrated. Review the different facts and try again."));return box;}

function start(){return el("div",{class:"start-screen"},[el("h1",{},"Module 08 — Broker Negotiation Lab"),el("p",{},"Twelve progressive stages and 24 occupational decisions. Build a position, verify facts, discover, counter, trade, protect authority, classify the closeout and hand off truthfully to Module 09."),el("p",{},"Critical failures are preserved as history and require a separate materially different reassessment; clicking a corrected answer on the original screen does not erase them."),el("button",{type:"button",class:"btn btn-primary btn-large",onclick:()=>{state={...state,startedAt:state.startedAt||Date.now()};save(state);render();}},state.startedAt?"Resume Simulation":"Start Simulation")]);}

function done(){const rec=computeCompletionRecord(state),review=rec.instructorReviewState!=="COMPLETE",c=el("div",{class:"completion-screen"},[el("h1",{},review?"Instructor Review Required":"Simulation Complete"),el("p",{},review?"The scenario and any required critical reassessments are recorded, but the commercial competency gate has not fully cleared.":"The premium SIM-008 competency gate has cleared.")]);c.appendChild(el("div",{class:"completion-stats"},[el("div",{class:"stat"},[el("div",{class:"stat-label"},"First Attempt"),el("div",{class:"stat-value"},`${rec.firstAttemptScore.correct} / ${rec.firstAttemptScore.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Scaled Practical"),el("div",{class:"stat-value"},`${rec.scaledPracticalScore} / 30`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Final Mastery"),el("div",{class:"stat-value"},`${rec.finalScore.correct} / ${rec.finalScore.total}`)])]));const list=el("div",{class:"competency-summary"},[el("h2",{},"Competency Summary")]);for(const[code,label]of Object.entries(COMPETENCY_LABELS))list.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${label}`),el("span",{class:"competency-status"},rec.competencies[code]||"In Progress")]));c.appendChild(list);const cf=el("div",{class:"competency-summary"},[el("h2",{},"Critical-Failure Record")]);for(const code of Object.keys(CRITICAL_FAILURE_FAMILIES))cf.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${CRITICAL_FAILURE_FAMILIES[code]}`),el("span",{class:"competency-status"},rec.criticalFailures[code])]));c.appendChild(cf);c.appendChild(el("button",{type:"button",class:"btn btn-text",onclick:()=>window.print()},"Print competency summary"));c.appendChild(el("p",{class:"next-step"},"Agreement in principle is not completed booking. Formal rate-confirmation review remains Module 09. This runtime stores evidence only in this browser; durable LMS/student-record integration and release QA remain deferred."));return c;}

function reset(){return el("button",{type:"button",class:"btn btn-text reset-btn",onclick:()=>{if(!confirm("Resetting erases this browser's SIM-008 attempt history. Reset?"))return;state=createInitialState();pending=null;feedback=false;save(state);render();}},"Reset simulation")}
function render(){root.innerHTML="";root.appendChild(el("header",{class:"app-header"},[el("div",{class:"app-title"},"Elite Dispatcher Academy — SIM-008 Premium"),reset()]));let body;if(!state.startedAt)body=start();else if(getNextUnresolvedCriticalFamily(state)&&DECISION_ORDER_COMPLETE())body=reassessmentScreen(getNextUnresolvedCriticalFamily(state));else if(state.status==="COMPLETE"||state.status==="INSTRUCTOR_REVIEW_REQUIRED")body=done();else body=decision(state.currentDecisionId);root.appendChild(el("main",{},body));}
function DECISION_ORDER_COMPLETE(){return Object.values(state.decisions).every(r=>r.firstAttemptResponse!==null);}
render();
