import {DECISIONS,STAGES,ARTIFACTS,COMPETENCY_LABELS} from "./content.js";
import {createInitialState,submitAttempt,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeFirstAttemptScore,computeFinalMasteryScore,computeRemediationCount,computeCompetencyStatus,getStageForDecision,getProgress,normalizeLoadedState} from "./logic.js";
const STORAGE_KEY="sim008-state-v1";
function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeLoadedState(JSON.parse(r)):null}catch{return null}}
function save(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
let state=load()||createInitialState(),pending=null,feedback=false;const root=document.getElementById("app");
function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==="class")n.className=v;else if(k.startsWith("on")&&typeof v==="function")n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}for(const c of [].concat(children)){if(c==null)continue;n.appendChild(typeof c==="string"?document.createTextNode(c):c)}return n;}
function artifact(key){const a=ARTIFACTS[key];if(!a)return null;const box=el("section",{class:"artifact-card","aria-label":a.title},[el("div",{class:"artifact-title"},a.title)]);for(const line of a.lines)box.appendChild(el("p",{},line));return box;}
function choice(d){const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.choices){const id=`c-${d.id}-${o.key}`,i=el("input",{type:"radio",name:d.id,id,value:o.key,onchange:()=>pending=o.key});if(pending===o.key)i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},o.key),el("span",{},o.text)]));}return f;}
function multi(d){if(!Array.isArray(pending))pending=[];const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.options){const id=`m-${d.id}-${o.key}`,i=el("input",{type:"checkbox",id,value:o.key,onchange:e=>{const s=new Set(pending);e.target.checked?s.add(o.key):s.delete(o.key);pending=[...s];}});if(pending.includes(o.key))i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{},o.text)]));}return f;}
function control(d){return d.type==="choice"?choice(d):multi(d)}
function complete(d){return d.type==="choice"?typeof pending==="string":Array.isArray(pending)&&pending.length>0}
function progress(id){const p=getProgress(id),s=getStageForDecision(id),si=STAGES.findIndex(x=>x.id===s.id)+1;return el("div",{class:"progress-bar",role:"status"},[el("div",{class:"progress-text"},`Stage ${si} of ${STAGES.length}: ${s.title} — Decision ${p.current} of ${p.total}`),el("div",{class:"progress-track"},[el("div",{class:"progress-fill",style:`width:${p.current/p.total*100}%`} )])]);}
function feedbackPanel(id){const d=DECISIONS[id],r=state.decisions[id],ok=r.finalCorrect,p=el("div",{class:`feedback-panel ${ok?"feedback-correct":"feedback-incorrect"}`,role:"alert"},[el("p",{class:"feedback-heading"},ok?"Correct":"Not yet"),el("p",{},ok?d.correctFeedback:d.remediation)]);if(r.instructorReviewRequired)p.appendChild(el("p",{class:"feedback-escalation"},"Repeated error on this critical decision has been flagged for instructor review. Your first-attempt evidence remains preserved."));const advance=shouldAdvance(state,id);p.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(advance){const next=getNextDecisionId(id);pending=null;feedback=false;if(next)state={...state,currentDecisionId:next};else state={...state,status:computeSimulationStatus(state),completedAt:Date.now()};save(state);render();}else{feedback=false;pending=null;render();}}},advance?"Continue":"Try again"));return p;}
function decision(id){const d=DECISIONS[id],c=el("div",{class:"decision-screen"},[progress(id)]);if(d.artifact)c.appendChild(artifact(d.artifact));c.appendChild(el("h2",{class:"decision-prompt"},d.prompt));if(!feedback){c.appendChild(control(d));c.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitAttempt(state,id,pending,Date.now());save(state);feedback=true;render();}},"Submit"));}else c.appendChild(feedbackPanel(id));return c;}
function start(){return el("div",{class:"start-screen"},[el("h1",{},"Module 08 — Broker Negotiation Lab"),el("p",{},"A fifteen-stage negotiation simulation. Prepare a position from verified facts, open professionally, discover and counter, protect authority, and close without confusing verbal agreement with formal booking."),el("p",{},"Operating framework: PREPARE → VERIFY FACTS → SET POSITION → OPEN → QUESTION → LISTEN → COUNTER → TRADE → CONFIRM → DOCUMENT → ACCEPT / DECLINE / ESCALATE."),el("button",{type:"button",class:"btn btn-primary btn-large",onclick:()=>{state={...state,startedAt:state.startedAt||Date.now()};save(state);render();}},state.startedAt?"Resume Simulation":"Start Simulation")]);}
function done(){const f=computeFirstAttemptScore(state),m=computeFinalMasteryScore(state),r=computeRemediationCount(state),cs=computeCompetencyStatus(state),review=state.status==="INSTRUCTOR_REVIEW_REQUIRED",c=el("div",{class:"completion-screen"},[el("h1",{},review?"Instructor Review Required":"Simulation Complete"),el("p",{},review?"The negotiation is finished, but a critical decision requires instructor follow-up before the Academy record can be cleared.":"You completed the broker negotiation workflow.")]);c.appendChild(el("div",{class:"completion-stats"},[el("div",{class:"stat"},[el("div",{class:"stat-label"},"First Attempt"),el("div",{class:"stat-value"},`${f.correct} / ${f.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Final Mastery"),el("div",{class:"stat-value"},`${m.correct} / ${m.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Remediation"),el("div",{class:"stat-value"},String(r))]) ]));const list=el("div",{class:"competency-summary"},[el("h2",{},"Competency Summary")]);for(const[code,label]of Object.entries(COMPETENCY_LABELS)){const s=cs[code]||"In Progress";list.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${label}`),el("span",{class:"competency-status"},s)]));}c.appendChild(list);c.appendChild(el("p",{class:"next-step"},"Verbal agreement within authority is not a completed booking. This build preserves simulation evidence only in local browser storage. Durable LMS/student-record integration and final release-layer QA remain deferred."));return c;}
function reset(){return el("button",{type:"button",class:"btn btn-text reset-btn",onclick:()=>{if(!confirm("Resetting erases this browser's SIM-008 attempt history. Reset?"))return;state=createInitialState();pending=null;feedback=false;save(state);render();}},"Reset simulation")}
function render(){root.innerHTML="";root.appendChild(el("header",{class:"app-header"},[el("div",{class:"app-title"},"Elite Dispatcher Academy — SIM-008"),reset()]));root.appendChild(el("main",{},!state.startedAt?start():(state.status==="COMPLETE"||state.status==="INSTRUCTOR_REVIEW_REQUIRED")?done():decision(state.currentDecisionId)));}
render();
