import {DECISIONS,STAGES,ARTIFACTS,COMPETENCY_LABELS} from "./content.js";
import {CRITICAL_FAILURE_FAMILIES,REASSESSMENTS} from "./reassessments.js";
import {createInitialState,submitAttempt,submitCriticalReassessment,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeCompletionRecord,getNextUnresolvedCriticalFamily,getStageForDecision,getProgress,normalizeLoadedState} from "./logic.js";
const STORAGE_KEY="sim007-premium-state-v2";
function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeLoadedState(JSON.parse(r)):null}catch{return null}}
function save(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
let state=load()||createInitialState(),pending=null,feedback=false;const root=document.getElementById("app");
function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==="class")n.className=v;else if(k.startsWith("on")&&typeof v==="function")n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}for(const c of [].concat(children)){if(c==null)continue;n.appendChild(typeof c==="string"?document.createTextNode(c):c)}return n;}
function artifact(key){const a=ARTIFACTS[key];if(!a)return null;const box=el("section",{class:"artifact-card","aria-label":a.title},[el("div",{class:"artifact-title"},a.title)]);for(const line of a.lines)box.appendChild(el("p",{},line));return box;}
function choice(d){const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.choices){const id=`c-${d.id}-${o.key}`,i=el("input",{type:"radio",name:d.id,id,value:o.key,onchange:()=>pending=o.key});if(pending===o.key)i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},o.key),el("span",{},o.text)]));}return f;}
function multi(d){if(!Array.isArray(pending))pending=[];const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.options){const id=`m-${d.id}-${o.key}`,i=el("input",{type:"checkbox",id,value:o.key,onchange:e=>{const s=new Set(pending);e.target.checked?s.add(o.key):s.delete(o.key);pending=[...s];}});if(pending.includes(o.key))i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{},o.text)]));}return f;}
function categorize(d){if(!pending||typeof pending!=="object"||Array.isArray(pending))pending={};const w=el("div",{class:"categorize-group"});for(const item of d.items){const row=el("fieldset",{class:"categorize-row"},[el("legend",{class:"categorize-item-text"},item.text)]);for(const b of d.buckets){const id=`cat-${d.id}-${item.key}-${b.key}`,i=el("input",{type:"radio",name:`cat-${d.id}-${item.key}`,id,value:b.key,onchange:()=>pending={...pending,[item.key]:b.key}});if(pending[item.key]===b.key)i.checked=true;row.appendChild(el("label",{for:id,class:"choice-option categorize-bucket-option"},[i,el("span",{},b.label)]));}w.appendChild(row);}return w;}
function numeric(d){const i=el("input",{type:"number",step:"any",class:"numeric-input",oninput:e=>pending=e.target.value===""?null:Number(e.target.value),"aria-label":d.prompt});if(typeof pending==="number")i.value=String(pending);return el("div",{class:"numeric-wrap"},[i,el("span",{},d.unit||"")]);}
function control(d){if(d.type==="choice")return choice(d);if(d.type==="multiselect")return multi(d);if(d.type==="categorize")return categorize(d);if(d.type==="numeric")return numeric(d);return multi(d);}
function complete(d){if(d.type==="choice")return typeof pending==="string";if(d.type==="numeric")return typeof pending==="number"&&!Number.isNaN(pending);if(d.type==="categorize")return pending&&typeof pending==="object"&&!Array.isArray(pending)&&d.items.every(i=>pending[i.key]);return Array.isArray(pending)&&pending.length>0;}
function progress(id){const p=getProgress(id),s=getStageForDecision(id),si=STAGES.findIndex(x=>x.id===s.id)+1;return el("div",{class:"progress-bar",role:"status"},[el("div",{class:"progress-text"},`Stage ${si} of ${STAGES.length}: ${s.title} — Decision ${p.current} of ${p.total}`),el("div",{class:"progress-track"},[el("div",{class:"progress-fill",style:`width:${p.current/p.total*100}%`} )])]);}
function advance(id){const next=getNextDecisionId(id);pending=null;feedback=false;if(next)state={...state,currentDecisionId:next};else state={...state,status:computeSimulationStatus(state)};save(state);render();}
function feedbackPanel(id){const d=DECISIONS[id],r=state.decisions[id],ok=r.finalCorrect,p=el("div",{class:`feedback-panel ${ok?"feedback-correct":"feedback-incorrect"}`,role:"alert"},[el("p",{class:"feedback-heading"},ok?"Correct":"Review required"),el("p",{},ok?d.correctFeedback:d.remediation)]);if(r.criticalFailureOccurred&&!r.criticalFailureResolved)p.appendChild(el("p",{class:"feedback-escalation"},`Critical evidence preserved: ${r.criticalFailureFamily}. Correcting this screen does not erase it. A materially different reassessment is required after the main scenario.`));const go=shouldAdvance(state,id);p.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>go?advance(id):(feedback=false,pending=null,render())},go?"Continue":"Try again"));return p;}
function decision(id){const d=DECISIONS[id],c=el("div",{class:"decision-screen"},[progress(id)]);if(d.artifact)c.appendChild(artifact(d.artifact));c.appendChild(el("h2",{class:"decision-prompt"},d.prompt));if(!feedback){c.appendChild(control(d));c.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitAttempt(state,id,pending,Date.now());save(state);feedback=true;render();}},"Submit"));}else c.appendChild(feedbackPanel(id));return c;}
function allMainAttempted(){return Object.values(state.decisions).every(r=>r.firstAttemptResponse!==null);}
function reassessment(family){const d=REASSESSMENTS[family],rr=state.reassessments[family],c=el("div",{class:"decision-screen"},[el("h1",{},"Critical Reassessment"),el("p",{},`${family}: ${CRITICAL_FAILURE_FAMILIES[family]}`),el("p",{},"This uses different facts. Your original response remains preserved in the competency record."),el("h2",{class:"decision-prompt"},d.prompt)]);c.appendChild(control(d));c.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitCriticalReassessment(state,family,pending,Date.now());pending=null;save(state);if(state.reassessments[family].resolved&&!getNextUnresolvedCriticalFamily(state))state={...state,status:computeSimulationStatus(state),completedAt:Date.now()};save(state);render();}},rr?.attemptCount?"Submit Reassessment Again":"Submit Reassessment"));if(rr?.attemptCount&&!rr.resolved)c.appendChild(el("p",{class:"feedback-escalation"},"Reassessment not yet demonstrated. Re-evaluate the different facts and try again."));return c;}
function start(){return el("div",{class:"start-screen"},[el("h1",{},"SIM-007 — Rate & Profitability Decision Desk"),el("p",{},"Ten progressive stages and 33 occupational decisions. Use total-trip economics, verified inputs and carrier-specific criteria rather than headline rate or loaded RPM alone."),el("p",{},"Critical failures remain in the record and require a separate materially different reassessment."),el("button",{type:"button",class:"btn btn-primary btn-large",onclick:()=>{state={...state,startedAt:state.startedAt||Date.now()};save(state);render();}},state.startedAt?"Resume Simulation":"Start Simulation")]);}
function done(){const r=computeCompletionRecord(state),review=r.instructorReviewState!=="COMPLETE",c=el("div",{class:"completion-screen"},[el("h1",{},review?"Instructor Review Required":"Simulation Complete"),el("p",{},review?"The scenario is recorded, but competency completion has not fully cleared.":"The SIM-007 content/runtime competency gate has cleared for this attempt.")]);c.appendChild(el("div",{class:"completion-stats"},[el("div",{class:"stat"},[el("div",{class:"stat-label"},"First Attempt"),el("div",{class:"stat-value"},`${r.firstAttemptScore.correct} / ${r.firstAttemptScore.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Final Mastery"),el("div",{class:"stat-value"},`${r.finalScore.correct} / ${r.finalScore.total}`)])]));const cs=el("div",{class:"competency-summary"},[el("h2",{},"Competency Summary")]);for(const[code,label]of Object.entries(COMPETENCY_LABELS))cs.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${label}`),el("span",{class:"competency-status"},r.competencies[code]||"In Progress")]));c.appendChild(cs);const cf=el("div",{class:"competency-summary"},[el("h2",{},"Critical-Failure Record")]);for(const code of Object.keys(CRITICAL_FAILURE_FAMILIES))cf.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${CRITICAL_FAILURE_FAMILIES[code]}`),el("span",{class:"competency-status"},r.criticalFailures[code])]));c.appendChild(cf);c.appendChild(el("button",{type:"button",class:"btn btn-text",onclick:()=>window.print()},"Print competency summary"));c.appendChild(el("p",{class:"next-step"},"This runtime stores evidence only in local browser storage. Durable LMS/student-record integration, browser/device QA and manual accessibility QA remain release-layer work."));return c;}
function reset(){return el("button",{type:"button",class:"btn btn-text reset-btn",onclick:()=>{if(!confirm("Resetting erases this browser's SIM-007 attempt history. Reset?"))return;state=createInitialState();pending=null;feedback=false;save(state);render();}},"Reset simulation")}
function render(){root.innerHTML="";root.appendChild(el("header",{class:"app-header"},[el("div",{class:"app-title"},"Elite Dispatcher Academy — SIM-007 Premium"),reset()]));let b;if(!state.startedAt)b=start();else if(allMainAttempted()&&getNextUnresolvedCriticalFamily(state))b=reassessment(getNextUnresolvedCriticalFamily(state));else if(state.status==="COMPLETE"||state.status==="INSTRUCTOR_REVIEW_REQUIRED")b=done();else b=decision(state.currentDecisionId);root.appendChild(el("main",{},b));}
render();
