import assert from "node:assert/strict";
import {readFileSync,existsSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname,resolve} from "node:path";
import {DECISION_ORDER,DECISIONS,COMPETENCY_LABELS} from "../content.js";
import {CRITICAL_FAMILIES,REASSESSMENTS} from "../critical-controls.js";
const here=dirname(fileURLToPath(import.meta.url));const repo=resolve(here,"../../../..");
let p=0,f=0;function t(n,fn){try{fn();p++;console.log(`PASS  ${n}`)}catch(e){f++;console.log(`FAIL  ${n}\n      ${e.message}`)}}
const required=["05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Student.md","05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Scenario-Packet.md","05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Instructor-Guide.md","05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Scoring-Rubric.md","05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Completion-Record.md","05-SIMULATIONS-AND-GAMES/Module-05/SIM-005-Premium-Critical-Reassessment-Addendum.md","05-SIMULATIONS-AND-GAMES/Module-05/runtime/README.md","03-ASSESSMENTS/Instructor-Guides/Module-05-Instructor-Guide.md","03-ASSESSMENTS/Practical-Assessments/Module-05-Practical.md","10-PRODUCTION/Module-05-Current-Source-Recheck-2026-09-05.md"];
t("required premium package files exist",()=>{for(const x of required)assert.ok(existsSync(resolve(repo,x)),x)});
t("nine controlled student tools remain present",()=>{const tools=["Module-05-Broker-Call-Sheet.md","Module-05-Broker-Verification-Worksheet.md","Module-05-Freight-Fraud-Red-Flag-Checklist.md","Module-05-Load-Comparison-Worksheet.md","Module-05-Load-Screening-Checklist.md","Module-05-Load-Search-Activity-Log.md","Module-05-Load-Search-Worksheet.md","Module-05-Rate-Confirmation-Review-Checklist.md","Module-05-STOP-VERIFY-ESCALATE-Load-Decision-Tool.md"];for(const x of tools)assert.ok(existsSync(resolve(repo,"04-STUDENT-TOOLS/Module-05-Tools",x)),x)});
t("runtime retains 18 decisions and all 14 competency families",()=>{assert.equal(DECISION_ORDER.length,18);assert.equal(Object.keys(COMPETENCY_LABELS).length,14);const used=new Set(DECISION_ORDER.map(id=>DECISIONS[id].competency));for(const k of Object.keys(COMPETENCY_LABELS))assert.ok(used.has(k),k)});
t("exactly six critical families and six materially different reassessments",()=>{assert.equal(Object.keys(CRITICAL_FAMILIES).length,6);assert.equal(Object.keys(REASSESSMENTS).length,6);for(const [cf,r] of Object.entries(REASSESSMENTS)){assert.equal(r.familyId,cf);assert.equal(r.materiallyDifferent,true)}});
t("practical and instructor controls describe the same six critical concepts",()=>{const practical=readFileSync(resolve(repo,"03-ASSESSMENTS/Practical-Assessments/Module-05-Practical.md"),"utf8");const guide=readFileSync(resolve(repo,"03-ASSESSMENTS/Instructor-Guides/Module-05-Instructor-Guide.md"),"utf8");const concepts=[/endorsement mismatch/i,/duplicate-looking/i,/verified brokerage entity/i,/rate confirmation/i,/signing authority/i,/(shipper-first|shipper bypasses|discretionary carrier allocation)/i];for(const re of concepts){assert.match(practical,re,`practical missing ${re}`);assert.match(guide,re,`guide missing ${re}`)}});
t("package explicitly prevents same-screen critical erasure",()=>{const rubric=readFileSync(resolve(repo,"05-SIMULATIONS-AND-GAMES/Module-05/Module-05-Simulation-Scoring-Rubric.md"),"utf8");const addendum=readFileSync(resolve(repo,"05-SIMULATIONS-AND-GAMES/Module-05/SIM-005-Premium-Critical-Reassessment-Addendum.md"),"utf8");assert.match(rubric,/same-screen correction[\s\S]{0,80}not\*{0,2} resolve|does\s*\*{0,2}not\*{0,2}\s*resolve/i);assert.match(addendum,/not erased|does not erase/i)});
t("currentness control distinguishes vendor rules from universal rules",()=>{const current=readFileSync(resolve(repo,"10-PRODUCTION/Module-05-Current-Source-Recheck-2026-09-05.md"),"utf8");assert.match(current,/Motus/);assert.match(current,/platform-specific|vendor-specific/i);assert.match(current,/not.*universal|must not.*universal/is)});
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
