import {DECISIONS,STAGES,ARTIFACTS,COMPETENCY_LABELS} from "./content.js";
import {createInitialState,submitAttempt,shouldAdvance,getNextDecisionId,computeSimulationStatus,computeFirstAttemptScore,computeFinalMasteryScore,computeRemediationCount,computeCompetencyStatus,computeCriticalFailureRecord,getStageForDecision,getProgress,normalizeLoadedState} from "./logic.js";
const STORAGE_KEY="sim006-state-v2";
function load(){try{const r=localStorage.getItem(STORAGE_KEY);return r?normalizeLoadedState(JSON.parse(r)):null}catch{return null}}
function save(s){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}
let state=load()||createInitialState(),pending=null,feedback=false;const root=document.getElementById("app");
function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==="class")n.className=v;else if(k.startsWith("on")&&typeof v==="function")n.addEventListener(k.slice(2),v);else n.setAttribute(k,v);}for(const c of [].concat(children)){if(c==null)continue;n.appendChild(typeof c==="string"?document.createTextNode(c):c)}return n;}
function artifact(key){const a=ARTIFACTS[key];if(!a)return null;const box=el("section",{class:"artifact-card","aria-label":a.title},[el("div",{class:"artifact-title"},a.title)]);for(const line of a.lines)box.appendChild(el("p",{},line));return box;}
function choice(d){const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.choices){const id=`c-${d.id}-${o.key}`,i=el("input",{type:"radio",name:d.id,id,value:o.key,onchange:()=>pending=o.key});if(pending===o.key)i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{class:"choice-key"},o.key),el("span",{},o.text)]));}return f;}
function multi(d){if(!Array.isArray(pending))pending=[];const f=el("fieldset",{class:"choice-group"},[el("legend",{class:"sr-only"},d.prompt)]);for(const o of d.options){const id=`m-${d.id}-${o.key}`,i=el("input",{type:"checkbox",id,value:o.key,onchange:e=>{const s=new Set(pending);e.target.checked?s.add(o.key):s.delete(o.key);pending=[...s];}});if(pending.includes(o.key))i.checked=true;f.appendChild(el("label",{for:id,class:"choice-option"},[i,el("span",{},o.text)]));}return f;}
function categorize(d){if(!pending||typeof pending!=="object"||Array.isArray(pending))pending={};const wrap=el("div",{class:"categorize-group"});for(const item of d.items){const row=el("fieldset",{class:"categorize-row"},[el("legend",{class:"categorize-item-text"},item.text)]);for(const b of d.buckets){const id=`cat-${d.id}-${item.key}-${b.key}`,i=el("input",{type:"radio",name:`cat-${d.id}-${item.key}`,id,value:b.key,onchange:()=>{pending={...pending,[item.key]:b.key};}});if(pending[item.key]===b.key)i.checked=true;row.appendChild(el("label",{for:id,class:"choice-option categorize-bucket-option"},[i,el("span",{},b.text||b.label)]));}wrap.appendChild(row);}return wrap;}
function control(d){if(d.type==="choice")return choice(d);if(d.type==="categorize")return categorize(d);return multi(d);}
function complete(d){if(d.type==="choice")return typeof pending==="string";if(d.type==="categorize")return pending&&typeof pending==="object"&&!Array.isArray(pending)&&d.items.every(i=>pending[i.key]);return Array.isArray(pending)&&pending.length>0;}
function progress(id){const p=getProgress(id),s=getStageForDecision(id),si=STAGES.findIndex(x=>x.id===s.id)+1;return el("div",{class:"progress-bar",role:"status"},[el("div",{class:"progress-text"},`Stage ${si} of ${STAGES.length}: ${s.title} — Decision ${p.current} of ${p.total}`),el("div",{class:"progress-track"},[el("div",{class:"progress-fill",style:`width:${p.current/p.total*100}%`})])]);}
function feedbackPanel(id){const d=DECISIONS[id],r=state.decisions[id],ok=r.finalCorrect,p=el("div",{class:`feedback-panel ${ok?"feedback-correct":"feedback-incorrect"}`,role:"alert"},[el("p",{class:"feedback-heading"},ok?"Correct":"Control failure"),el("p",{},ok?d.correctFeedback:d.remediation)]);if(r.criticalFailureOccurred)p.appendChild(el("p",{class:"feedback-escalation"},`Critical competency evidence preserved: ${r.criticalFailureFamily}. Same-screen correction cannot erase this event; materially different reassessment is required.`));const advance=shouldAdvance(state,id);p.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(advance){const next=getNextDecisionId(id);pending=null;feedback=false;if(next)state={...state,currentDecisionId:next};else state={...state,status:computeSimulationStatus(state),completedAt:Date.now()};save(state);render();}else{feedback=false;pending=null;render();}}},advance?"Continue":"Try again"));return p;}
function decision(id){const d=DECISIONS[id],c=el("div",{class:"decision-screen"},[progress(id)]);if(d.artifact)c.appendChild(artifact(d.artifact));c.appendChild(el("h2",{class:"decision-prompt"},d.prompt));if(!feedback){c.appendChild(control(d));c.appendChild(el("button",{type:"button",class:"btn btn-primary",onclick:()=>{if(!complete(d))return;state=submitAttempt(state,id,pending,Date.now());save(state);feedback=true;render();}},"Submit"));}else c.appendChild(feedbackPanel(id));return c;}
function start(){return el("div",{class:"start-screen"},[el("h1",{},"Module 06 — Broker Verification & Fraud Command Desk"),el("p",{},"A ten-stage progressive verification simulation. A legitimate broker entity is deliberately mixed with conflicting contact, document, payment, and duplicate-posting evidence. Your job is disciplined verification—not maximum suspicion."),el("p",{},"Operating framework: RECEIVE → ISOLATE CLAIMS → VERIFY ENTITY → AUTHENTICATE CONTACT → CROSS-CHECK LOAD/DOCUMENTS → VERIFY PAYMENT PATH → RECORD EVIDENCE → CLASSIFY RISK → PROCEED / VERIFY / HOLD / ESCALATE / DECLINE."),el("p",{},"Critical failures are preserved as competency evidence and require instructor review plus reassessment on a materially different case."),el("button",{type:"button",class:"btn btn-primary btn-large",onclick:()=>{state={...state,startedAt:state.startedAt||Date.now()};save(state);render();}},state.startedAt?"Resume Simulation":"Start Simulation")]);}
function done(){const f=computeFirstAttemptScore(state),m=computeFinalMasteryScore(state),r=computeRemediationCount(state),cs=computeCompetencyStatus(state),critical=computeCriticalFailureRecord(state),review=state.status==="INSTRUCTOR_REVIEW_REQUIRED",c=el("div",{class:"completion-screen"},[el("h1",{},review?"Instructor Review Required":"Simulation Complete"),el("p",{},review?"The case traversal is finished, but preserved critical-failure evidence prevents clean competency clearance. Complete targeted remediation and materially different reassessment.":"You completed the broker verification and fraud-prevention workflow without a preserved critical failure.")]);c.appendChild(el("div",{class:"completion-stats"},[el("div",{class:"stat"},[el("div",{class:"stat-label"},"First Attempt"),el("div",{class:"stat-value"},`${f.correct} / ${f.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Final Mastery"),el("div",{class:"stat-value"},`${m.correct} / ${m.total}`)]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Remediation"),el("div",{class:"stat-value"},String(r))]),el("div",{class:"stat"},[el("div",{class:"stat-label"},"Critical Failures"),el("div",{class:"stat-value"},String(critical.length))]) ]));if(critical.length){const cf=el("div",{class:"competency-summary"},[el("h2",{},"Preserved Critical-Failure Evidence")]);for(const x of critical)cf.appendChild(el("div",{class:"competency-row"},[el("span",{},`${x.decisionId}: ${x.family}`),el("span",{class:"competency-status"},"Instructor Review")]));c.appendChild(cf);}const list=el("div",{class:"competency-summary"},[el("h2",{},"Competency Summary")]);for(const[code,label]of Object.entries(COMPETENCY_LABELS)){const s=cs[code]||"In Progress";list.appendChild(el("div",{class:"competency-row"},[el("span",{},`${code}: ${label}`),el("span",{class:"competency-status"},s)]));}c.appendChild(list);c.appendChild(el("p",{class:"next-step"},"This browser build preserves local attempt evidence only. Durable LMS/student-record integration, browser/device matrix, manual accessibility review, and assembled release QA remain deferred."));return c;}
function reset(){return el("button",{type:"button",class:"btn btn-text reset-btn",onclick:()=>{if(!confirm("Resetting erases this browser's local SIM-006 attempt history. Reset?"))return;state=createInitialState();pending=null;feedback=false;save(state);render();}},"Reset simulation");}
function render(){root.innerHTML="";root.appendChild(el("header",{class:"app-header"},[el("div",{class:"app-title"},"Elite Dispatcher Academy — SIM-006"),reset()]));root.appendChild(el("main",{},!state.startedAt?start():(state.status==="COMPLETE"||state.status==="INSTRUCTOR_REVIEW_REQUIRED")?done():decision(state.currentDecisionId)));}
render();
