// SIM-006 premium content — Module 06 Broker Verification & Fraud Command Desk.
export const STAGES=[
{id:"SIM06-S1",title:"Intake — Isolate Claims and Evidence States",decisionIds:["SIM06-D01","SIM06-D02"]},
{id:"SIM06-S2",title:"Entity Verification",decisionIds:["SIM06-D03","SIM06-D04"]},
{id:"SIM06-S3",title:"Contact Authentication",decisionIds:["SIM06-D05","SIM06-D06","SIM06-D07"]},
{id:"SIM06-S4",title:"Load and Document Cross-Check",decisionIds:["SIM06-D08","SIM06-D09"]},
{id:"SIM06-S5",title:"Financial Security and Current-Status Interpretation",decisionIds:["SIM06-D10","SIM06-D11"]},
{id:"SIM06-S6",title:"Duplicate / Re-brokering Ambiguity",decisionIds:["SIM06-D12","SIM06-D13"]},
{id:"SIM06-S7",title:"Payment-Path Attack",decisionIds:["SIM06-D14","SIM06-D15"]},
{id:"SIM06-S8",title:"Urgency and Social-Engineering Pressure",decisionIds:["SIM06-D16","SIM06-D17"]},
{id:"SIM06-S9",title:"Evidence-State Change and Reclassification",decisionIds:["SIM06-D18","SIM06-D19"]},
{id:"SIM06-S10",title:"Final Disposition and Escalation Packet",decisionIds:["SIM06-D20","SIM06-D21","SIM06-D22"]}];

export const ARTIFACTS={
intake:{title:"Release 1 — Incoming claim",lines:["Posting: Kestrel Logistics Group; dry van Amarillo TX → Springfield MO; $2,150; self-reported MC/callback.","Email from dispatch@kestrel-logisticsgroup.com references the exact posting. No prior carrier relationship."]},
entity:{title:"Release 2 — Entity record",lines:["Authoritative FMCSA/Motus-style training record: Kestrel exists; required broker authority ACTIVE; financial-responsibility filing current at lookup.","Independent general-company contact route is listed. This record does not identify the person emailing you."]},
contact:{title:"Release 3 — Channel mismatch",lines:["Inbound domain: kestrel-logisticsgroup.com. Independently located corporate domain: kestrellogistics.com.","Email says: 'Use this direct line—main office is slow.'"]},
callback:{title:"Release 4 — Trusted callback",lines:["Independent company callback confirms Kestrel is legitimate but cannot authenticate sender/domain or locate the questioned load reference.","Company asks carrier not to rely on the questioned contact while it investigates."]},
docs:{title:"Release 5 — Document cross-check",lines:["Posting: Kestrel Logistics Group; correct MC; $2,150; Amarillo → Springfield.","Rate confirmation: 'Kestrel Logistic Group'; MC differs by one digit; pickup reference differs; lane/rate match; questioned domain in footer."]},
financial:{title:"Release 6A — Status evidence",lines:["Training snapshot: current BMC-85 filing; factor/credit portal shows Kestrel acceptable under that private provider's policy.","Neither authenticates the sender/load/document/payment path. Keep 7-calendar-day, 7-business-day, and 30-day regulatory contexts separate."]},
inactive:{title:"Release 6B — Alternate authority mini-case",lines:["Alder Ridge Brokerage LLC is real; matching domain/contact; clean-looking document; required broker authority is INACTIVE in current authoritative evidence.","Contact calls it a 'system delay' and asks you to dispatch now."]},
duplicate:{title:"Release 7 — Similar posting",lines:["Second posting has same general lane/equipment/window/commodity family but another broker/rate.","Could be separate freight, stale duplicate, authorized co-brokering, or unauthorized re-brokering. Evidence is incomplete."]},
payment:{title:"Release 8 — Remittance change",lines:["Questioned sender requests immediate ACH/remittance change and supplies new banking data plus a confirmation number only inside the email.","No prior payment relationship; trusted company callback has not authenticated this sender."]},
pressure:{title:"Release 9 — Pressure",lines:["'Confirm in five minutes or we move the load.' 'Compliance approved it.' 'Do not call the main line again.'","No new verifying evidence; material contact/document/payment gaps remain."]},
later:{title:"Release 10 — State change",lines:["Trusted Kestrel compliance confirms entity/authority remain valid but questioned sender/domain is NOT authorized.","Rate confirmation was not issued through Kestrel process; Kestrel did not request the payment change. Similar posting remains unresolved."]},
final:{title:"Final case file",lines:["Entity VERIFIED; contact CONTRADICTED; document CONTRADICTED; payment path CONTRADICTED; duplicate indicator UNRESOLVED.","No booking, dispatch, signature, credential sharing, or payment change proceeded."]}};

export const COMPETENCY_LABELS={
C01:"Classify intake",C02:"Separate claims from facts",C03:"Verify entity",C04:"Separate entity/contact",C05:"Authenticate contact",C06:"Cross-check documents",C07:"Interpret current-status evidence",C08:"Handle duplicate ambiguity",C09:"Protect payment path",C10:"Resist pressure",C11:"Preserve evidence states",C12:"Reclassify risk",C13:"Choose disposition",C14:"Build escalation handoff"};

const ch=(id,s,c,a,p,x,k,f,r,e={})=>({id,stageId:s,type:"choice",competency:c,artifact:a,prompt:p,choices:x,correctKey:k,correctFeedback:f,remediation:r,...e});
const mu=(id,s,c,a,p,x,k,f,r,e={})=>({id,stageId:s,type:"multiselect",competency:c,artifact:a,prompt:p,options:x,correctSet:k,correctFeedback:f,remediation:r,...e});
const ca=(id,s,c,a,p,i,b,m,f,r,e={})=>({id,stageId:s,type:"categorize",competency:c,artifact:a,prompt:p,items:i,buckets:b,correctMap:m,correctFeedback:f,remediation:r,...e});
const O=(key,text)=>({key,text});

export const DECISIONS={
"SIM06-D01":ca("SIM06-D01","SIM06-S1","C01","intake","Classify each intake item.",[O("name","Broker name on posting"),O("email","An email arrived"),O("sender","Sender is authorized"),O("auth","MC authority is active")],[O("known","KNOWN"),O("claimed","CLAIMED"),O("unknown","UNKNOWN / VERIFY")],{name:"claimed",email:"known",sender:"unknown",auth:"unknown"},"Correct: observable receipt is known; self-reported or identity/status claims require verification.","Specific-looking claims are still claims. Separate observation from what the source wants you to believe."),
"SIM06-D02":ch("SIM06-D02","SIM06-S1","C02","intake","Best first operational move?",[O("A","Call the email's number"),O("B","Separate entity/contact/load-document/payment claims and build independent verification paths"),O("C","Trust the sender because lane/rate match"),O("D","Accuse fraud from the unfamiliar domain")],"B","Correct: build the verification map before acting.","The first move is neither trust nor accusation; isolate claims and select independent evidence."),
"SIM06-D03":mu("SIM06-D03","SIM06-S2","C03","entity","What does the authoritative entity evidence support?",[O("exists","Entity exists"),O("active","Authority active"),O("bmc","Financial filing current"),O("sender","Sender authorized"),O("load","Load authentic")],["exists","active","bmc"],"Correct: entity/status evidence proves only the entity/status facts shown.","Do not stretch an entity record into contact, load, document, or payment authentication."),
"SIM06-D04":ch("SIM06-D04","SIM06-S2","C04","entity","May active legitimate entity status authenticate this email sender?",[O("A","Yes"),O("B","No; authenticate the contact independently"),O("C","Yes if company name matches"),O("D","Yes if rate is reasonable")],"B","Correct: ENTITY VERIFICATION IS NOT CONTACT VERIFICATION.","A real company can be impersonated. Treating entity status as contact authorization is critical.",{criticalFailureFamily:"CF2_ENTITY_AS_CONTACT_PROOF"}),
"SIM06-D05":ch("SIM06-D05","SIM06-S3","C05","contact","How should the domain mismatch be treated?",[O("A","Ignore it"),O("B","Unresolved contact signal; independently authenticate"),O("C","Reply asking the sender to verify itself"),O("D","Declare fraud")],"B","Correct: mismatch triggers verification, not automatic trust or accusation.","A questioned channel cannot authenticate itself; construct an independent route."),
"SIM06-D06":ch("SIM06-D06","SIM06-S3","C05","contact","Which callback route is defensible?",[O("A","Number inside questioned email"),O("B","Number independently obtained from authoritative/official source"),O("C","First random search result"),O("D","Sender's text number")],"B","Correct: trusted callback information must be independently sourced.","Calling contact data supplied by the questioned party is circular verification."),
"SIM06-D07":ch("SIM06-D07","SIM06-S3","C05","callback","Trusted callback contradicts sender identity/load claim. What now?",[O("A","Proceed because entity is active"),O("B","STOP/DO NOT BOOK questioned transaction; preserve and escalate"),O("C","Keep negotiating"),O("D","Send credentials for proof")],"B","Correct: confirmed contact contradiction is a stop condition for this transaction.","Proceeding through confirmed contact contradiction is critical; entity legitimacy cannot cure it.",{criticalFailureFamily:"CF3_PROCEED_THROUGH_CONTACT_CONTRADICTION"}),
"SIM06-D08":mu("SIM06-D08","SIM06-S4","C06","docs","Which fields actually mismatch?",[O("legalName","Broker name"),O("mc","MC number"),O("pickupRef","Pickup/reference"),O("rate","Rate"),O("lane","Lane")],["legalName","mc","pickupRef"],"Correct: name, MC, and reference conflict; rate/lane match.","Professional verification flags actual discrepancies, not everything that feels suspicious."),
"SIM06-D09":ch("SIM06-D09","SIM06-S4","C06","docs","Treatment of unresolved document mismatches?",[O("A","Silently correct and sign"),O("B","HOLD reliance; record mismatches; require verified/corrected documentation"),O("C","Declare broker fraudulent"),O("D","Dispatch because lane/rate match")],"B","Correct: material mismatches remain HOLD/VERIFY until independently resolved.","Bypassing a material unresolved identity/document/payment mismatch is critical.",{criticalFailureFamily:"CF6_BYPASS_MATERIAL_MISMATCH"}),
"SIM06-D10":ch("SIM06-D10","SIM06-S5","C07","financial","Best interpretation of BMC and factor/credit evidence?",[O("A","Together they authenticate sender and guarantee payment"),O("B","BMC supports current financial-responsibility status; factor approval is private commercial-risk evidence; neither authenticates this transaction"),O("C","Any seven-day rule creates a seven-day safety window"),O("D","They erase document mismatches")],"B","Correct: each evidence source has limited meaning; separate regulatory clocks remain separate.","Financial security and factor status are not contact authentication, fraud findings, or payment guarantees."),
"SIM06-D11":ch("SIM06-D11","SIM06-S5","C07","inactive","Alder Ridge authority is verified INACTIVE. Contact says system delay. Decision?",[O("A","Book now"),O("B","Do not book; HOLD/DECLINE until authoritative status supports proceeding"),O("C","Book with written promise"),O("D","Ignore if documents match")],"B","Correct: verified inactive required authority blocks the supplied booking.","Knowingly proceeding while required authority is verified inactive is critical.",{criticalFailureFamily:"CF4_PROCEED_WITH_INACTIVE_AUTHORITY"}),
"SIM06-D12":ch("SIM06-D12","SIM06-S6","C08","duplicate","What does the similar posting establish by itself?",[O("A","Conclusive double brokering"),O("B","Ambiguous verification indicator; not proof by itself"),O("C","Both brokers legitimate"),O("D","Always harmless")],"B","Correct: similar postings can have multiple innocent or improper explanations.","A red flag is not a proven conclusion. Verify the relationship/authorization facts."),
"SIM06-D13":ch("SIM06-D13","SIM06-S6","C08","duplicate","Best evidence-record language?",[O("A","Confirmed double-broker scam"),O("B","Similar posting observed; authorization/relationship unresolved; verify independently"),O("C","Both brokers committed fraud"),O("D","No action needed")],"B","Correct: document observation, uncertainty, and next verification step.","Declaring fraud/double brokering solely from inconclusive indicators is critical.",{criticalFailureFamily:"CF5_UNSUPPORTED_FRAUD_CONCLUSION"}),
"SIM06-D14":ch("SIM06-D14","SIM06-S7","C09","payment","First response to unexpected remittance change?",[O("A","Apply new ACH"),O("B","HOLD change; preserve instructions; independently authenticate"),O("C","Call only number in same email then change"),O("D","Apply if bank format looks valid")],"B","Correct: unexpected payment changes are HOLD/VERIFY until independently authenticated.","Acting on unverified/contradicted payment redirection is critical.",{criticalFailureFamily:"CF1_ACT_ON_PAYMENT_REDIRECTION"}),
"SIM06-D15":mu("SIM06-D15","SIM06-S7","C09","payment","What belongs in the payment-change record?",[O("incoming","Original request/channel/time"),O("source","Trusted-source construction"),O("authority","Who confirmed and authority"),O("result","Verification result"),O("pressure","Pressure language"),O("guess","Personal honesty guess")],["incoming","source","authority","result","pressure"],"Correct: preserve auditable facts, authority, result, and pressure.","A handoff must be reconstructable without relying on dispatcher intuition."),
"SIM06-D16":ch("SIM06-D16","SIM06-S8","C10","pressure","Five-minute deadline, no new evidence. What changes?",[O("A","Nothing; verification threshold stays"),O("B","Trust temporarily"),O("C","Ignore mismatches"),O("D","Send partial credentials")],"A","Correct: urgency changes pressure, not evidence requirements.","A deadline is not verification evidence; do not trade a critical control for the load."),
"SIM06-D17":ch("SIM06-D17","SIM06-S8","C10","pressure","Sender claims compliance approval and says stop calling main line. Response?",[O("A","Accept claimed approval"),O("B","Verify approval through actual authorized carrier/company records; maintain HOLD/ESCALATE"),O("C","Call sender a scammer"),O("D","Bypass carrier owner")],"B","Correct: claimed authority must be authenticated through the real authorization path.","Pressure to bypass controls increases—not decreases—the need for independent verification."),
"SIM06-D18":ca("SIM06-D18","SIM06-S9","C11","later","Classify evidence after Kestrel compliance responds.",[O("entity","Entity/authority"),O("contact","Sender/domain"),O("document","Rate confirmation"),O("payment","Payment change"),O("duplicate","Similar posting")],[O("verified","VERIFIED"),O("contradicted","CONTRADICTED"),O("unresolved","UNRESOLVED")],{entity:"verified",contact:"contradicted",document:"contradicted",payment:"contradicted",duplicate:"unresolved"},"Correct: keep each evidence bucket in its own state.","Bad transaction evidence does not retroactively make the legitimate entity fake; unresolved duplicate evidence stays unresolved."),
"SIM06-D19":ch("SIM06-D19","SIM06-S9","C12","later","Correct reclassification after new compliance evidence?",[O("A","CLEAR because entity legitimate"),O("B","DO NOT BOOK / ESCALATE questioned transaction"),O("C","Fraud proven against Kestrel company"),O("D","VERIFY only; no stop")],"B","Correct: new evidence strengthens the transaction stop without accusing the legitimate entity.","Reclassify from evidence, not from first impressions or unsupported accusations."),
"SIM06-D20":ch("SIM06-D20","SIM06-S10","C13","final","Final operational disposition?",[O("A","PROCEED"),O("B","DO NOT BOOK / DECLINE questioned transaction and ESCALATE preserved evidence"),O("C","Proceed pickup only"),O("D","Keep negotiating")],"B","Correct: contradicted contact/document/payment evidence makes this transaction non-actionable.","Proceeding around material identity/document/payment gaps is critical.",{criticalFailureFamily:"CF6_BYPASS_MATERIAL_MISMATCH"}),
"SIM06-D21":mu("SIM06-D21","SIM06-S10","C14","final","What must the escalation packet contain?",[O("verified","Verified facts/source/time"),O("unresolved","Unverified/contradicted claims"),O("actions","Verification actions/results"),O("stopped","Actions stopped"),O("owner","Owner + decision requested"),O("evidence","Preserved evidence references"),O("opinion","Personal crime accusation")],["verified","unresolved","actions","stopped","owner","evidence"],"Correct: professional escalation is factual, reconstructable, and routed to a decision owner.","Escalation is not 'ask somebody'; preserve evidence, stopped actions, owner, and next decision."),
"SIM06-D22":ch("SIM06-D22","SIM06-S10","C14","final","Which closeout statement is defensible?",[O("A","Kestrel is a fraudulent broker"),O("B","Questioned transaction declined because contact/document/payment instructions were independently contradicted; legitimate entity record remains separate; evidence escalated"),O("C","Duplicate proves double brokering"),O("D","We were suspicious, so we passed")],"B","Correct: transaction findings remain separate from unsupported accusations against the legitimate entity.","State what was verified, contradicted, unresolved, stopped, and escalated; suspicion is not evidence.")};

export const DECISION_ORDER=STAGES.flatMap(s=>s.decisionIds);
