// SIM-004 content data. Fictional training records; no sibling simulation imports.
export const STAGES = [
  {id:"SIM04-S1",title:"Carrier File Intake",decisionIds:["SIM04-D01","SIM04-D02"]},
  {id:"SIM04-S2",title:"Authority / Insurance Reconciliation",decisionIds:["SIM04-D03","SIM04-D04"]},
  {id:"SIM04-S3",title:"W-9 / Entity Reconciliation",decisionIds:["SIM04-D05","SIM04-D06"]},
  {id:"SIM04-S4",title:"Driver & Equipment Profiles",decisionIds:["SIM04-D07","SIM04-D08"]},
  {id:"SIM04-S5",title:"Credential / Endorsement Event",decisionIds:["SIM04-D09","SIM04-D10"]},
  {id:"SIM04-S6",title:"Current Medical-Certification Event",decisionIds:["SIM04-D11","SIM04-D12"]},
  {id:"SIM04-S7",title:"Payment Change Event",decisionIds:["SIM04-D13","SIM04-D14"]},
  {id:"SIM04-S8",title:"Scope / Compliance Request",decisionIds:["SIM04-D15","SIM04-D16"]},
  {id:"SIM04-S9",title:"Expiration / Policy / Authority Routing",decisionIds:["SIM04-D17","SIM04-D18"]},
  {id:"SIM04-S10",title:"Integrated Onboarding Disposition",decisionIds:["SIM04-D19","SIM04-D20"]},
];

export const ARTIFACTS = {
  intake:{title:"Lone Star Ridge — Intake Packet",lines:["Required carrier authority: current-status record supplied as active","COI: supplied","W-9: supplied; name differs from FMCSA entity display","Payment: existing NOA to Factor One","Driver profiles: two supplied","Equipment profile: one tractor / one 53-ft dry van" ]},
  authorityInsurance:{title:"Authority + Insurance File",lines:["Current official-source result: required operating authority active","COI: $750,000 public-liability information for the fictional non-hazmat ≥10,001-lb operating category","COI issue date: recent","Reminder: COI is represented insurance information; it is not operating authority"]},
  w9:{title:"Entity Reconciliation File",lines:["FMCSA record: Lone Star Ridge Transport LLC","W-9 Line 1: Jordan Ridge","W-9 Line 2: Lone Star Ridge Transport LLC","Tax/entity relationship documentation: not yet reconciled in onboarding notes"]},
  profiles:{title:"Operational Profiles",lines:["Driver A: contact current; Class A; assigned tractor/trailer; availability current; H/X not needed for ordinary dry-van work","Driver B: Class A; assigned equipment; NO H or X endorsement on file","Equipment: 53-ft dry van; unit numbers captured; no reefer capability","Carrier restriction: no NYC; maximum preferred deadhead 150 miles"]},
  hazmat:{title:"Proposed Load — Driver B",lines:["Fictional shipment: placarded hazardous material","Training-file requirement: H or X endorsement","Assigned driver: Driver B","Verified profile: Driver B has no H or X endorsement"]},
  currentMedicalEvent:{title:"CURRENT-DATE TRAINING EVENT — NRII / Paper MEC",currentDateSensitive:true,lines:["Training date: September 2026","Driver A paper MEC: issued 35 days ago","Electronic medical-certification record: not yet updated","Current Academy source control: temporary nationwide exemption scheduled April 11–October 11, 2026; paper MEC may be relied on for up to 60 days subject to its terms","Required Academy control: verify certificate/driver match and carrier process; dispatcher does not make the final regulatory qualification determination","REVERIFY BEFORE USE AFTER OCTOBER 11, 2026 OR IF FMCSA PROCEDURE CHANGES"]},
  payment:{title:"Payment Direction Event",lines:["Existing NOA: remit to Factor One","New text: 'Change all payments to Ridge Direct Bank immediately'","Sender number: not previously verified","Message includes a new callback number","No independent confirmation has occurred"]},
  scope:{title:"Carrier Owner Request",lines:["Owner: 'Since you already keep driver profiles, take over our full DQ files too.'","Owner also asks dispatcher to run Clearinghouse queries and administer drug/alcohol compliance","Current dispatch agreement: ordinary dispatch services; no separate compliance-service scope is defined"]},
  tracker:{title:"Currentness + Policy File",lines:["Driver A CDL expiration: hard credential date on file","UCR: recurring annual registration item","Operating authority: current status must be checked for the relevant dispatch decision","COI re-request every 90 days: carrier's internal review policy","Carrier preference: no NYC","After-hours contact: safety manager receives compliance escalations; carrier owner authorizes service-scope changes"]},
  finalFile:{title:"Final Onboarding Reconciliation",lines:["Required authority: active in supplied current-source result","COI: supplied; evidence limits understood","W-9/entity relationship: still needs documented reconciliation","Driver A: operational profile complete; current medical event verified only under then-current procedure","Driver B: cannot take the stated hazmat load without the stated required endorsement","Payment: existing NOA remains; new redirect request unverified","Compliance-program request: outside ordinary dispatch scope pending separate scope/competency/legal review","Equipment profile: operationally usable for ordinary dry-van sourcing","Carrier preferences and escalation contacts: documented"]}
};

export const COMPETENCY_LABELS={
 A:"Carrier identity / authority source selection",B:"Insurance / COI evidence limits",C:"W-9 / entity reconciliation",D:"Dispatch profile vs DQ/compliance boundary",E:"Driver/equipment profile completeness",F:"CDL/endorsement compatibility",G:"Current medical-certification verification discipline",H:"Payment-change verification",I:"Expiration/currentness classification",J:"Carrier policy vs legal requirement",K:"Decision-authority routing",L:"Integrated onboarding disposition"
};

const choice=(id,stageId,competency,artifact,prompt,choices,correctKey,correctFeedback,remediation,extra={})=>({id,stageId,type:"choice",competency,artifact,prompt,choices,correctKey,correctFeedback,remediation,...extra});
const multi=(id,stageId,competency,artifact,prompt,options,correctSet,correctFeedback,remediation,extra={})=>({id,stageId,type:"multiselect",competency,artifact,prompt,options,correctSet,correctFeedback,remediation,...extra});
const seq=(id,stageId,competency,artifact,prompt,items,correctOrder,correctFeedback,remediation,extra={})=>({id,stageId,type:"sequencing",competency,artifact,prompt,items,correctOrder,correctFeedback,remediation,...extra});

export const DECISIONS={
 "SIM04-D01":choice("SIM04-D01","SIM04-S1","L","intake","What is the correct first judgment about this packet?",[{key:"A",text:"READY because all major document names are present"},{key:"B",text:"INTAKE RECEIVED — reconcile currentness, matches, authority and unresolved items before readiness"},{key:"C",text:"DO NOT USE because a W-9 name differs"}],"B","Correct. Document presence starts review; it does not finish verification.","Onboarding is operational readiness, not PDF collection."),
 "SIM04-D02":multi("SIM04-D02","SIM04-S1","L",null,"Which categories must be reconciled before an integrated readiness decision?",[{key:"authority",text:"Authority/current registration"},{key:"insurance",text:"Insurance evidence"},{key:"w9",text:"W-9/entity relationship"},{key:"payment",text:"Payment/factoring instructions"},{key:"drivers",text:"Driver operational readiness"},{key:"equipment",text:"Equipment profile"},{key:"logo",text:"Whether the carrier logo looks expensive"}], ["authority","insurance","w9","payment","drivers","equipment"],"Correct. These are material onboarding categories; branding appearance is not verification.","Use the Module 04 onboarding checklist categories, not cosmetic signals."),
 "SIM04-D03":choice("SIM04-D03","SIM04-S2","A","authorityInsurance","Which evidence establishes the supplied current authority fact in this scenario?",[{key:"A",text:"The COI"},{key:"B",text:"The carrier's email signature"},{key:"C",text:"The supplied current official-source authority result"},{key:"D",text:"The W-9"}],"C","Correct. Use the current authoritative source appropriate to the authority fact.","A COI, W-9 or email signature does not prove current operating authority."),
 "SIM04-D04":multi("SIM04-D04","SIM04-S2","B",null,"Which controls belong in a professional insurance/authority reconciliation?",[{key:"coiSummary",text:"Treat the COI as represented insurance information"},{key:"currentAuthority",text:"Check current authority/status separately"},{key:"entityMatch",text:"Reconcile entity names and relevant dates/limits"},{key:"coiAuthority",text:"Treat the COI as proof of authority"}], ["coiSummary","currentAuthority","entityMatch"],"Correct. Keep document evidence, entity match and current authority verification separate.","The central misconception is COI = authority. It does not."),
 "SIM04-D05":choice("SIM04-D05","SIM04-S3","C","w9","How should the W-9/FMCSA name pattern be classified before the relationship is documented?",[{key:"A",text:"Confirmed fraud"},{key:"B",text:"VERIFY / RECONCILE the tax/entity relationship"},{key:"C",text:"Ignore it because W-9 names never matter"}],"B","Correct. A naming difference can have a legitimate tax/entity explanation; verify it without accusation.","Mismatch is a verification event, not proof of fraud."),
 "SIM04-D06":multi("SIM04-D06","SIM04-S3","C",null,"What should the onboarding record contain to resolve this discrepancy professionally?",[{key:"taxRelationship",text:"Documentation/explanation of the tax/entity relationship"},{key:"trustedDocs",text:"Appropriate trusted documentation/contact verification"},{key:"neutralNote",text:"A neutral reconciliation note stating what was verified"},{key:"publicAccusation",text:"A public fraud accusation before verification"}], ["taxRelationship","trustedDocs","neutralNote"],"Correct. Reconcile facts and document the result without unsupported accusations.","Professional language separates a mismatch from a conclusion of wrongdoing."),
 "SIM04-D07":choice("SIM04-D07","SIM04-S4","D","profiles","What is the Driver Dispatch Profile in Module 04?",[{key:"A",text:"The carrier's full federally required DQ file"},{key:"B",text:"A substitute for the CDL"},{key:"C",text:"A narrower operational record containing information reasonably needed to dispatch"},{key:"D",text:"A broker registration record"}],"C","Correct. Operational dispatch information and carrier compliance records have different purposes and owners.","The dispatch profile is deliberately narrower than the carrier's DQ/compliance record."),
 "SIM04-D08":multi("SIM04-D08","SIM04-S4","E",null,"Which driver-profile facts are operationally useful before dispatching?",[{key:"availability",text:"Current availability"},{key:"assignedEquipment",text:"Assigned equipment"},{key:"endorsements",text:"Applicable endorsements"},{key:"contact",text:"Current contact/communication method"},{key:"medicalStatus",text:"Medical qualification status/expiration where operationally needed"},{key:"diagnosis",text:"Underlying private medical diagnosis details"}], ["availability","assignedEquipment","endorsements","contact","medicalStatus"],"Correct. Capture operationally necessary status, not unnecessary private medical detail.","Use data minimization: status/expiration where needed, not underlying diagnoses."),
 "SIM04-D09":choice("SIM04-D09","SIM04-S5","F","hazmat","How should Driver B be classified for this fictional load?",[{key:"A",text:"PROCEED because Driver B has a Class A CDL"},{key:"B",text:"PROCEED and obtain the endorsement later"},{key:"C",text:"DO NOT DISPATCH Driver B on this load — the scenario states the required H/X qualification is missing"},{key:"D",text:"Change trailers and proceed"}],"C","Correct. The stated driver/load qualification conflict controls this assignment.","A general CDL or different trailer does not cure a stated missing required endorsement.",{escalateAfterAttempts:2}),
 "SIM04-D10":choice("SIM04-D10","SIM04-S5","F",null,"What should the dispatcher document after rejecting Driver B for this load?",[{key:"A",text:"That Driver B is unqualified for every commercial load forever"},{key:"B",text:"That the current file does not support dispatching Driver B on this specific stated load; route to another lawful assignment/qualified driver"},{key:"C",text:"That the broker committed fraud"}],"B","Correct. Document the specific incompatibility and next safe action without overgeneralizing.","The decision is load-specific on the supplied facts."),
 "SIM04-D11":choice("SIM04-D11","SIM04-S6","G","currentMedicalEvent","Under the current training event, what is the dispatcher-level response?",[{key:"A",text:"Automatically clear the driver because the paper MEC is under 60 days old"},{key:"B",text:"VERIFY the paper certificate, driver match and carrier process under the then-current procedure; do not make a final dispatcher-level regulatory qualification determination"},{key:"C",text:"Automatically reject every paper MEC"},{key:"D",text:"Ignore medical qualification status entirely"}],"B","Correct. The time window is one fact in a verification process, not a substitute for identity/process verification or carrier responsibility.","This is current-date material. Verify under the then-current procedure and preserve the dispatch/compliance boundary.",{currentDateSensitive:true}),
 "SIM04-D12":multi("SIM04-D12","SIM04-S6","G",null,"Which facts must be checked before the current training event can support an operational proceed decision?",[{key:"issueDate",text:"Certificate issue date/current procedure"},{key:"driverMatch",text:"Certificate corresponds to the correct driver"},{key:"carrierProcess",text:"Carrier's current process/understanding is confirmed"},{key:"dispatcherFinal",text:"Dispatcher independently declares final medical qualification"}], ["issueDate","driverMatch","carrierProcess"],"Correct. Verify the evidence and process without taking over the carrier's final compliance role.","Do not convert an operational verification step into a final regulatory determination."),
 "SIM04-D13":choice("SIM04-D13","SIM04-S7","H","payment","What should happen to the new payment instruction?",[{key:"A",text:"Update immediately because the message sounds urgent"},{key:"B",text:"STOP the change and independently verify through a previously trusted channel before any update"},{key:"C",text:"Use the callback number inside the same unverified message as the sole verification"},{key:"D",text:"Ask the driver to choose the bank"}],"B","Correct. An inbound request is not its own authentication.","Use a previously verified channel; do not let the questionable message verify itself.",{escalateAfterAttempts:2}),
 "SIM04-D14":seq("SIM04-D14","SIM04-S7","H",null,"Put the Module 04 payment-change control in order.",[{key:"stop",text:"STOP — do not act on the inbound change"},{key:"trusted",text:"Use a previously verified contact method"},{key:"callback",text:"Callback / independently verify"},{key:"compare",text:"Compare entity/account/factor information"},{key:"document",text:"Document the verification"},{key:"update",text:"Update only after confirmation"}], ["stop","trusted","callback","compare","document","update"],"Correct. Authentication precedes change.","The workflow is STOP → trusted channel → verify → compare → document → update."),
 "SIM04-D15":choice("SIM04-D15","SIM04-S8","D","scope","What is the correct response to the carrier owner's request?",[{key:"A",text:"Accept automatically because the dispatcher already has driver information"},{key:"B",text:"Accept automatically because the owner asked verbally"},{key:"C",text:"OUTSIDE ORDINARY DISPATCH PROFILE — stop and require separate scope, competency, responsibility, data-handling and contract/legal review before taking on a compliance service"},{key:"D",text:"Refuse all future communication with the carrier"}],"C","Correct. Operational information possession does not create compliance-program authority or competency.","Do not silently expand ordinary dispatching into DQ/Clearinghouse/drug-alcohol administration.",{escalateAfterAttempts:2}),
 "SIM04-D16":choice("SIM04-D16","SIM04-S8","K",null,"Who should own the next decision about whether a separate compliance service will exist?",[{key:"A",text:"The dispatcher alone, because they have the spreadsheet"},{key:"B",text:"Carrier ownership/appropriate compliance/legal/contract decision-makers under a separately defined scope"},{key:"C",text:"The driver with the most seniority"}],"B","Correct. Decision authority follows role, scope and competency — not possession of records.","Knowing how to contact people is not the same as having authority to redefine the service."),
 "SIM04-D17":multi("SIM04-D17","SIM04-S9","I","tracker","Match the four currentness categories by selecting all correctly stated pairings.",[{key:"legalExpiration",text:"CDL expiration → LEGAL EXPIRATION"},{key:"annualRenewal",text:"UCR → ANNUAL RENEWAL"},{key:"loadByLoad",text:"Current operating authority → LOAD-BY-LOAD CHECK when relevant to dispatch"},{key:"companyReview",text:"90-day COI re-request → COMPANY/BEST-PRACTICE REVIEW in this fictional carrier policy"},{key:"coiFederal90",text:"90-day COI re-request → universal federal legal deadline"}], ["legalExpiration","annualRenewal","loadByLoad","companyReview"],"Correct. Do not turn a company review cadence into a universal legal deadline.","Keep legal expiration, annual renewal, fresh dispatch verification and company review separate."),
 "SIM04-D18":choice("SIM04-D18","SIM04-S9","J","tracker","The carrier's 'no NYC' rule is best classified as:",[{key:"A",text:"A universal federal trucking law"},{key:"B",text:"A broker authority regulation"},{key:"C",text:"Carrier policy / operational preference that the dispatcher must honor for this client"},{key:"D",text:"A CDL endorsement"}],"C","Correct. It matters operationally because the carrier chose it, not because it is a universal law.","Professional dispatching labels the source of a requirement accurately."),
 "SIM04-D19":choice("SIM04-D19","SIM04-S10","L","finalFile","What is the best integrated onboarding disposition?",[{key:"A",text:"READY with no qualifications because authority is active"},{key:"B",text:"HOLD / READY ONLY WITH DOCUMENTED QUALIFICATIONS: reconcile W-9, keep payment redirect stopped, do not use Driver B for stated hazmat load, and do not assume compliance-program scope"},{key:"C",text:"DO NOT USE the carrier permanently because several items need verification"},{key:"D",text:"Ignore unresolved items and begin dispatching every driver/load"}],"B","Correct. Different parts of the file can carry different statuses; unresolved material items must remain visible and controlled.","An integrated readiness decision does not erase item-level holds, load-specific disqualifications or scope boundaries."),
 "SIM04-D20":multi("SIM04-D20","SIM04-S10","L",null,"Which unresolved controls must appear in the final onboarding handoff?",[{key:"w9",text:"W-9/entity reconciliation remains open"},{key:"payment",text:"Unverified payment redirect remains stopped"},{key:"driverB",text:"Driver B cannot take the stated hazmat load on the supplied profile"},{key:"scope",text:"Compliance-program request requires separate scope/competency review"},{key:"authority",text:"Pretend authority is inactive even though the supplied current result says active"}], ["w9","payment","driverB","scope"],"Correct. Preserve the actual open issues without inventing a new one.","Final documentation should show what is verified, what is open, what is stopped, and who owns the next action.")
};

export const DECISION_ORDER=STAGES.flatMap(s=>s.decisionIds);
