// SIM-005 content data. Fictional training records; no sibling simulation imports.
export const STAGES = [
  {id:"SIM05-S1",title:"Search Profile & Parameters",decisionIds:["SIM05-D01","SIM05-D02"]},
  {id:"SIM05-S2",title:"Candidate A — Strong Initial Lead",decisionIds:["SIM05-D03"]},
  {id:"SIM05-S3",title:"Candidate B — Stale Posting",decisionIds:["SIM05-D04"]},
  {id:"SIM05-S4",title:"Candidate C — Incomplete Posting",decisionIds:["SIM05-D05","SIM05-D06"]},
  {id:"SIM05-S5",title:"Candidate D — Endorsement Conflict",decisionIds:["SIM05-D07"]},
  {id:"SIM05-S6",title:"Candidate E — Carrier Policy Conflict",decisionIds:["SIM05-D08"]},
  {id:"SIM05-S7",title:"Duplicate Postings Event",decisionIds:["SIM05-D09"]},
  {id:"SIM05-S8",title:"Entity vs Contact Event",decisionIds:["SIM05-D10"]},
  {id:"SIM05-S9",title:"Rate Confirmation Review",decisionIds:["SIM05-D11","SIM05-D12"]},
  {id:"SIM05-S10",title:"Timing / HOS Feasibility",decisionIds:["SIM05-D13"]},
  {id:"SIM05-S11",title:"Factor / Credit Signal",decisionIds:["SIM05-D14"]},
  {id:"SIM05-S12",title:"Shipper-First Allocation Request",decisionIds:["SIM05-D15"]},
  {id:"SIM05-S13",title:"Progressive Update & Final Disposition",decisionIds:["SIM05-D16","SIM05-D17"]},
];

export const ARTIFACTS = {
  searchInputs:{title:"Carrier / Driver / Equipment Profile",lines:["Carrier: Meridian Cross Logistics — represented carrier","Equipment: 53-ft dry van; no reefer capability","Driver: Class A; no H, N, or X endorsement on file","Carrier preference: no NYC; maximum preferred deadhead 150 miles","Current position: Dallas, TX area, empty tomorrow morning"]},
  candidateA:{title:"Candidate A — Board Posting",lines:["Origin: Dallas, TX (matches current position)","Destination: Atlanta, GA","Equipment: dry van, matches","Commodity: general freight, non-hazmat","Rate posted; broker phone-confirmed load still open"]},
  candidateB:{title:"Candidate B — Board Posting",lines:["Posted 22 hours ago","Origin/destination/equipment appear to match search profile","No availability confirmation has been obtained yet"]},
  candidateC:{title:"Candidate C — Board Posting",lines:["Origin and equipment type shown","Destination: not shown","Weight/commodity: not shown","Pickup date/appointment: not shown"]},
  candidateD:{title:"Candidate D — Board Posting",lines:["Commodity: placarded hazardous material","Required qualification: H or X endorsement","Assigned driver profile: no H, N, or X endorsement on file"]},
  candidateE:{title:"Candidate E — Board Posting",lines:["Destination: New York, NY (5 boroughs)","Carrier standing preference on file: no NYC","Otherwise matches equipment and commodity profile"]},
  duplicatePostings:{title:"Duplicate Postings Observed",lines:["Two postings, same origin/destination/equipment, different company names","Reference numbers differ","Rates differ slightly","No independent verification has occurred yet"]},
  entityContact:{title:"Broker Contact Event",lines:["Brokerage entity: verified active in a current official-source check","New inbound contact: phone number not previously used for this brokerage","Contact claims to be a new dispatcher at the verified brokerage","No independent confirmation of this specific contact has occurred"]},
  rateConfirmation:{title:"Supplied Rate Confirmation",lines:["Negotiated verbally: $2,450 all-in, no additional stops","Rate confirmation received: $2,200 all-in, one additional stop added","Broker identity and load reference number match what was discussed","Discrepancy has not yet been raised with the broker"]},
  timingQuestion:{title:"Timing Question",lines:["Candidate load: 640 miles, requested delivery within 11 hours of pickup","Driver's actual current available hours: not yet checked in this file","Posting alone does not state driver-specific feasibility"]},
  factorSignal:{title:"Factor/Credit Signal",lines:["Carrier's factoring company declined to purchase an invoice from this broker last month","No other information about the reason is supplied","Broker's current official-source authority status: active in a current check"]},
  shipperRequest:{title:"Shipper-First Contact",lines:["A shipper (not a broker) contacts the dispatcher directly","Shipper: 'We have several loads this week — just pick whichever of your carriers can take each one'","Dispatcher represents more than one carrier"]},
  updateEvent:{title:"New Information — Candidate A Revisited",lines:["New fact: Candidate A's origin facility now shows a 4-hour appointment delay for tomorrow's pickup window","This changes Candidate A's relative attractiveness compared to other still-open candidates"]},
};

export const COMPETENCY_LABELS={
 A:"Search profile construction",B:"Search parameter setting",C:"FOUND vs VERIFIED AVAILABLE",D:"Equipment/commodity/qualification screening",E:"Missing-information verification questions",F:"Candidate comparison",G:"Entity vs contact verification",H:"Red-flag response without unsupported accusation",I:"Rate-confirmation discrepancy handling",J:"Signing-authority boundary",K:"Timing/HOS feasibility verification",L:"Credit/factor signal classification",M:"Shipper-first allocation-scope escalation"
};

const choice=(id,stageId,competency,artifact,prompt,choices,correctKey,correctFeedback,remediation,extra={})=>({id,stageId,type:"choice",competency,artifact,prompt,choices,correctKey,correctFeedback,remediation,...extra});
const multi=(id,stageId,competency,artifact,prompt,options,correctSet,correctFeedback,remediation,extra={})=>({id,stageId,type:"multiselect",competency,artifact,prompt,options,correctSet,correctFeedback,remediation,...extra});

export const DECISIONS={
 "SIM05-D01":multi("SIM05-D01","SIM05-S1","A","searchInputs","Which facts belong in the search profile built from this carrier/driver/equipment file?",[{key:"equipment",text:"Equipment type and capability (dry van, no reefer)"},{key:"qualifications",text:"Driver's current endorsements (none on file)"},{key:"position",text:"Current position and empty date"},{key:"preferences",text:"Carrier preferences (no NYC, max deadhead)"},{key:"unrelatedPast",text:"An unrelated load the carrier hauled six months ago"}], ["equipment","qualifications","position","preferences"],"Correct. These facts define what a viable candidate must actually satisfy.","An old, unrelated load doesn't define what this specific search should target."),
 "SIM05-D02":choice("SIM05-D02","SIM05-S1","B",null,"How should the search radius/parameters be set?",[{key:"A",text:"Always exactly 150 miles regardless of the file"},{key:"B",text:"Based on the carrier's stated preferences, current position, and market conditions — not a fixed universal number"},{key:"C",text:"As wide as possible with no limit"},{key:"D",text:"Whatever the load board defaults to"}],"B","Correct. Search parameters follow the specific carrier's actual preferences and conditions.","There is no single correct radius that applies to every carrier and every search."),
 "SIM05-D03":choice("SIM05-D03","SIM05-S2","C","candidateA","How should Candidate A be classified right now?",[{key:"A",text:"FOUND only — a phone confirmation doesn't count as verification"},{key:"B",text:"GOOD CANDIDATE — equipment, commodity, and route match, and availability has been independently phone-confirmed"},{key:"C",text:"BAD FIT — the destination is unfamiliar"},{key:"D",text:"STOP / ESCALATE — no reason given"}],"B","Correct. A phone-confirmed, fully matching candidate is a good candidate for further evaluation.","Don't underclassify a candidate that has already cleared both the fit check and the availability check."),
 "SIM05-D04":choice("SIM05-D04","SIM05-S3","C","candidateB","How should Candidate B be classified based on the facts given?",[{key:"A",text:"GOOD CANDIDATE — the posting looks complete"},{key:"B",text:"FOUND — a potentially relevant match has been located, but availability has not been VERIFIED"},{key:"C",text:"VERIFIED AVAILABLE — posting age doesn't matter"},{key:"D",text:"BAD FIT — posted over 12 hours ago means automatically gone"}],"B","Correct. A posting matching the profile is FOUND, not VERIFIED AVAILABLE, until availability is actually confirmed.","Posting age is a priority signal, not proof either way — and a matching posting is still only FOUND until confirmed."),
 "SIM05-D05":choice("SIM05-D05","SIM05-S4","E","candidateC","How should Candidate C be classified?",[{key:"A",text:"GOOD CANDIDATE — equipment matches"},{key:"B",text:"NEEDS MORE INFORMATION / VERIFY — destination, weight/commodity, and pickup date are all missing"},{key:"C",text:"BAD FIT — incomplete postings are always rejected"},{key:"D",text:"STOP / ESCALATE — this is a fraud indicator"}],"B","Correct. Missing material fields require verification, not an assumption in either direction.","An incomplete posting isn't automatically bad or automatically good — it needs the missing facts filled in."),
 "SIM05-D06":multi("SIM05-D06","SIM05-S4","E",null,"Turn the missing information into specific verification questions to ask the broker.",[{key:"destination",text:"What is the exact delivery destination?"},{key:"weight",text:"What is the commodity and weight?"},{key:"pickup",text:"What is the pickup date/appointment window?"},{key:"unrelated",text:"What color is the broker's office building?"}], ["destination","weight","pickup"],"Correct. These are the actual missing facts that matter to a booking decision.","Ask about what's actually missing and material, not irrelevant details."),
 "SIM05-D07":choice("SIM05-D07","SIM05-S5","D","candidateD","How should Candidate D be classified for this driver?",[{key:"A",text:"GOOD CANDIDATE — the driver holds a valid CDL"},{key:"B",text:"GOOD CANDIDATE — the endorsement can be obtained after booking"},{key:"C",text:"BAD FIT / REJECT for this driver — the required H or X endorsement is missing on the supplied profile"},{key:"D",text:"NEEDS MORE INFORMATION — ask the broker to waive the requirement"}],"C","Correct. A stated required-endorsement gap controls this candidate for this driver, regardless of CDL validity.","A valid CDL alone does not satisfy a specific placarded-hazmat endorsement requirement.",{escalateAfterAttempts:2}),
 "SIM05-D08":choice("SIM05-D08","SIM05-S6","D","candidateE","How should Candidate E be classified given the carrier's on-file preference?",[{key:"A",text:"GOOD CANDIDATE — the carrier can be asked to make an exception"},{key:"B",text:"BAD FIT / REJECT — conflicts with the carrier's documented standing preference (no NYC)"},{key:"C",text:"GOOD CANDIDATE — carrier preferences aren't real constraints"},{key:"D",text:"STOP / ESCALATE — this is a legal violation"}],"B","Correct. A documented carrier constraint is a real operational conflict, even though it's not a legal violation.","Carrier policy conflicts are real reasons to reject a candidate, without needing to escalate them as a legal issue."),
 "SIM05-D09":choice("SIM05-D09","SIM05-S7","H","duplicatePostings","What is the correct response to these duplicate-looking postings?",[{key:"A",text:"Declare double brokering has occurred and refuse to work with either company"},{key:"B",text:"VERIFY the relationship/status through an appropriate source before drawing any conclusion — duplicate postings alone don't prove fraud"},{key:"C",text:"Ignore the duplication entirely since rates differ slightly"},{key:"D",text:"Book whichever posting has the higher rate"}],"B","Correct. Duplicate-looking postings are a verification trigger, not proof of double brokering on their own.","Declaring proven fraud from a duplicate posting alone is an unsupported accusation.",{escalateAfterAttempts:2}),
 "SIM05-D10":choice("SIM05-D10","SIM05-S8","G","entityContact","What is the correct response to this new contact?",[{key:"A",text:"Proceed normally — the brokerage entity is already verified active"},{key:"B",text:"Verify this specific contact independently (e.g., through the brokerage's main line) before treating them as authorized — entity verification does not by itself authenticate a new individual contact"},{key:"C",text:"Refuse all future contact with this brokerage"},{key:"D",text:"Assume the contact is fraudulent since the number is new"}],"B","Correct. A verified brokerage entity does not automatically make an unfamiliar individual contact authorized — verify the contact separately.","Entity verification and contact authentication are two separate checks; passing one doesn't pass the other.",{escalateAfterAttempts:2}),
 "SIM05-D11":choice("SIM05-D11","SIM05-S9","I","rateConfirmation","What should happen with this rate confirmation?",[{key:"A",text:"Sign it — the broker and load reference match, so the rest is a formality"},{key:"B",text:"STOP and raise the discrepancy with the broker before signing — the rate and stop count don't match what was negotiated"},{key:"C",text:"Sign it and adjust the invoice later to the negotiated amount"},{key:"D",text:"Ignore the rate confirmation and rely on the verbal agreement only"}],"B","Correct. A material discrepancy between negotiated terms and the written document requires resolution before signing.","Matching broker/reference identity doesn't cure a real rate and scope discrepancy elsewhere in the document.",{escalateAfterAttempts:2}),
 "SIM05-D12":choice("SIM05-D12","SIM05-S9","J",null,"Who has the authority to sign this rate confirmation on the carrier's behalf?",[{key:"A",text:"Whoever is reviewing the document, by default"},{key:"B",text:"Whoever the carrier's actual Dispatch Agreement or LPOA authorizes for this action — reviewing a document doesn't itself grant signing authority"},{key:"C",text:"Any dispatcher, always"},{key:"D",text:"The broker decides who signs"}],"B","Correct. Signing authority comes from the carrier's actual authorization, not from the act of reviewing the document.","Do not assume signing authority simply because you're the one looking at the paperwork.",{escalateAfterAttempts:2}),
 "SIM05-D13":choice("SIM05-D13","SIM05-S10","K","timingQuestion","What is the correct response to this timing question?",[{key:"A",text:"Calculate feasibility from distance and time alone: 640 miles in 11 hours is achievable at highway speed, so approve it"},{key:"B",text:"Verify the driver's actual current available hours and duty status before committing to this schedule"},{key:"C",text:"Reject automatically — any tight timing is disqualifying"},{key:"D",text:"Assume it's fine since the broker posted that window"}],"B","Correct. Real feasibility depends on the driver's actual current hours, not a distance-only calculation.","Distance-and-time math alone doesn't establish HOS feasibility — verify the driver's real current status."),
 "SIM05-D14":choice("SIM05-D14","SIM05-S11","L","factorSignal","How should this factor decline be classified?",[{key:"A",text:"Proof the broker committed fraud"},{key:"B",text:"A private financial-risk decision by the factor — not proof of fraud and not proof the broker lost its operating authority"},{key:"C",text:"Proof the broker's authority is currently inactive"},{key:"D",text:"Irrelevant and not worth noting anywhere"}],"B","Correct. A factor decline reflects that factor's own risk assessment — it doesn't itself prove fraud or authority loss.","Don't convert a private financial-risk signal into a legal or safety conclusion it doesn't support."),
 "SIM05-D15":choice("SIM05-D15","SIM05-S12","M","shipperRequest","How should this shipper request be classified?",[{key:"A",text:"Consistent with Carrier-Side Agency — sourcing for represented carriers is normal"},{key:"B",text:"SIGNIFICANT BROKERAGE RISK — discretionary allocation of shipper-supplied freight among multiple represented carriers; STOP and escalate rather than proceeding as ordinary sourcing"},{key:"C",text:"NEEDS MORE INFORMATION — ask the shipper for a written contract first"},{key:"D",text:"Fine as long as the dispatcher doesn't charge the shipper directly"}],"B","Correct. Choosing which of several represented carriers gets shipper-supplied freight is the allocation-of-traffic pattern that presents brokerage risk.","This is not ordinary carrier-side sourcing — it's the discretionary-allocation pattern Module 02 treats as a real boundary issue.",{escalateAfterAttempts:2}),
 "SIM05-D16":choice("SIM05-D16","SIM05-S13","F","updateEvent","Given this new appointment-delay fact, what should happen to Candidate A's standing?",[{key:"A",text:"No change — Candidate A was already confirmed, so new facts don't matter"},{key:"B",text:"Re-evaluate Candidate A against other still-open candidates in light of the new delay before finalizing a shortlist"},{key:"C",text:"Automatically drop Candidate A entirely"},{key:"D",text:"Ignore the update since it came in late"}],"B","Correct. New material facts should be weighed against other live candidates, not ignored or overreacted to.","A confirmed candidate isn't exempt from being re-evaluated when a material new fact arrives."),
 "SIM05-D17":multi("SIM05-D17","SIM05-S13","F",null,"Which items belong in the final documented disposition for this search session?",[{key:"shortlist",text:"Updated shortlist reflecting the Candidate A delay"},{key:"rejected",text:"Rejected candidates with reasons (D, E)"},{key:"open",text:"Still-open verification items (Candidate C's missing fields, the rate-confirmation discrepancy)"},{key:"escalated",text:"Escalated items (shipper-first request, duplicate postings if unresolved)"},{key:"invented",text:"A new conclusion not supported by anything in this session"}], ["shortlist","rejected","open","escalated"],"Correct. Document what's actually known, open, rejected, and escalated — nothing invented.","Final documentation should reflect the real state of this session, not a tidier story than the facts support.")
};

export const DECISION_ORDER=STAGES.flatMap(s=>s.decisionIds);
