import {DECISIONS,DECISION_ORDER,STAGES} from "./content.js";
import {CRITICAL_FAMILIES,REASSESSMENTS,familyForDecision} from "./critical-controls.js";
export function createInitialState(){const decisions={};for(const id of DECISION_ORDER)decisions[id]={firstAttemptResponse:null,firstAttemptCorrect:null,firstAttemptTimestamp:null,finalResponse:null,finalCorrect:null,remediationUsed:false,attemptCount:0,finalTimestamp:null,instructorReviewRequired:false,criticalFailureOccurred:false,criticalFailureFamily:null,criticalFailureTimestamp:null};const criticalFailures={};const reassessments={};for(const cf of Object.keys(CRITICAL_FAMILIES)){criticalFailures[cf]={occurred:false,triggerDecisionId:CRITICAL_FAMILIES[cf].decisionId,triggerTimestamp:null,resolved:false,resolvedTimestamp:null};reassessments[cf]={attemptCount:0,firstResponse:null,firstCorrect:null,finalResponse:null,finalCorrect:null,timestamp:null};}return{simulationId:"SIM-005",currentDecisionId:DECISION_ORDER[0],decisions,criticalFailures,reassessments,status:"IN_PROGRESS",startedAt:null,completedAt:null};}
function seteq(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length)return false;const A=new Set(a),B=new Set(b);if(A.size!==B.size)return false;for(const v of A)if(!B.has(v))return false;return true;}
export function evaluateResponse(id,response){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);if(d.type==="choice")return response===d.correctKey;if(d.type==="multiselect")return seteq(response,d.correctSet);if(d.type==="sequencing")return Array.isArray(response)&&response.length===d.correctOrder.length&&d.correctOrder.every((v,i)=>response[i]===v);throw new Error(`Unknown decision type: ${d.type}`);}
export function submitAttempt(state,id,response,now=Date.now()){const d=DECISIONS[id];if(!d)throw new Error(`Unknown decision: ${id}`);const r={...state.decisions[id]},correct=evaluateResponse(id,response);if(r.firstAttemptResponse===null){r.firstAttemptResponse=response;r.firstAttemptCorrect=correct;r.firstAttemptTimestamp=now;}else r.remediationUsed=true;r.attemptCount+=1;r.finalResponse=response;r.finalCorrect=correct;r.finalTimestamp=now;let criticalFailures={...state.criticalFailures};const family=familyForDecision(id);if(!correct&&d.escalateAfterAttempts&&r.attemptCount>=d.escalateAfterAttempts){r.instructorReviewRequired=true;if(family){r.criticalFailureOccurred=true;r.criticalFailureFamily=family;if(r.criticalFailureTimestamp===null)r.criticalFailureTimestamp=now;const prior=criticalFailures[family]||{};criticalFailures[family]={...prior,occurred:true,triggerDecisionId:id,triggerTimestamp:prior.triggerTimestamp??now,resolved:false,resolvedTimestamp:null};}}else if(correct){r.instructorReviewRequired=Boolean(family&&criticalFailures[family]?.occurred&&!criticalFailures[family]?.resolved);}return{...state,decisions:{...state.decisions,[id]:r},criticalFailures};}
export function submitReassessment(state,familyId,response,now=Date.now()){const ra=REASSESSMENTS[familyId];if(!ra)throw new Error(`Unknown reassessment family: ${familyId}`);const existing=state.reassessments?.[familyId]||{attemptCount:0,firstResponse:null,firstCorrect:null,finalResponse:null,finalCorrect:null,timestamp:null};const correct=response===ra.correctKey;const record={...existing,attemptCount:existing.attemptCount+1,finalResponse:response,finalCorrect:correct,timestamp:now};if(existing.firstResponse===null){record.firstResponse=response;record.firstCorrect=correct;}const criticalFailures={...state.criticalFailures};const cf={...criticalFailures[familyId]};if(correct&&cf?.occurred){criticalFailures[familyId]={...cf,resolved:true,resolvedTimestamp:now};}const decisionId=CRITICAL_FAMILIES[familyId].decisionId;const decisions={...state.decisions,[decisionId]:{...state.decisions[decisionId],instructorReviewRequired:!(correct&&cf?.occurred)}};return{...state,reassessments:{...state.reassessments,[familyId]:record},criticalFailures,decisions};}
export function computeCriticalFailureStatus(state){const out={};for(const cf of Object.keys(CRITICAL_FAMILIES)){const r=state.criticalFailures?.[cf];out[cf]=!r?.occurred?"NOT_TRIGGERED":r.resolved?"RESOLVED_BY_REASSESSMENT":"REASSESSMENT_REQUIRED";}return out;}
export function shouldAdvance(state,id){const r=state.decisions[id];return r.finalCorrect===true||r.instructorReviewRequired===true;}
export function getNextDecisionId(id){const i=DECISION_ORDER.indexOf(id);return i<0||i===DECISION_ORDER.length-1?null:DECISION_ORDER[i+1];}
export function computeSimulationStatus(state){if(Object.values(computeCriticalFailureStatus(state)).some(v=>v==="REASSESSMENT_REQUIRED"))return"INSTRUCTOR_REVIEW_REQUIRED";if(Object.values(state.decisions).some(r=>r.instructorReviewRequired))return"INSTRUCTOR_REVIEW_REQUIRED";if(DECISION_ORDER.every(id=>state.decisions[id].finalCorrect===true))return"COMPLETE";return"IN_PROGRESS";}
export function computeFirstAttemptScore(state){return{correct:DECISION_ORDER.filter(id=>state.decisions[id].firstAttemptCorrect===true).length,total:DECISION_ORDER.length};}
export function computeFinalMasteryScore(state){return{correct:DECISION_ORDER.filter(id=>state.decisions[id].finalCorrect===true).length,total:DECISION_ORDER.length};}
export function computeRemediationCount(state){return DECISION_ORDER.filter(id=>state.decisions[id].remediationUsed).length;}
export function computeCompetencyStatus(state){const map={};for(const id of DECISION_ORDER)(map[DECISIONS[id].competency]??=[]).push(id);const out={};for(const[c,ids]of Object.entries(map)){const rs=ids.map(id=>state.decisions[id]);if(rs.some(r=>r.instructorReviewRequired))out[c]="Needs Instructor Review";else if(rs.some(r=>r.finalCorrect===null))out[c]="In Progress";else if(rs.every(r=>r.finalCorrect===true&&!r.remediationUsed))out[c]="Mastered";else if(rs.every(r=>r.finalCorrect===true))out[c]="Mastered After Remediation";else out[c]="In Progress";}return out;}
export function computeCompletionRecord(state){return{simulationId:"SIM-005",status:computeSimulationStatus(state),firstAttemptScore:computeFirstAttemptScore(state),finalMasteryScore:computeFinalMasteryScore(state),remediationCount:computeRemediationCount(state),competencies:computeCompetencyStatus(state),criticalFailures:computeCriticalFailureStatus(state),reassessments:state.reassessments,instructorReviewState:Object.values(computeCriticalFailureStatus(state)).some(v=>v==="REASSESSMENT_REQUIRED")?"REASSESSMENT_REQUIRED":"CLEAR"};}
export function getStageForDecision(id){const d=DECISIONS[id];return d?STAGES.find(s=>s.id===d.stageId)||null:null;}
export function getProgress(id){const i=DECISION_ORDER.indexOf(id);return{current:i+1,total:DECISION_ORDER.length};}
export function normalizeLoadedState(raw){if(!raw||typeof raw!=="object"||raw.simulationId!=="SIM-005"||!raw.decisions||typeof raw.decisions!=="object")return createInitialState();const fresh=createInitialState(),decisions={};for(const id of DECISION_ORDER){const saved=raw.decisions[id];decisions[id]=saved&&typeof saved==="object"?{...fresh.decisions[id],...saved}:fresh.decisions[id];}const criticalFailures={...fresh.criticalFailures,...(raw.criticalFailures||{})};const reassessments={...fresh.reassessments,...(raw.reassessments||{})};return{...fresh,...raw,decisions,criticalFailures,reassessments,currentDecisionId:DECISION_ORDER.includes(raw.currentDecisionId)?raw.currentDecisionId:DECISION_ORDER[0]};}
