import assert from "node:assert/strict";
import {STAGES,DECISIONS,DECISION_ORDER,COMPETENCY_LABELS} from "../content.js";
import {createInitialState,submitAttempt,computeCriticalFailureStatus,computeCompletionRecord} from "../logic.js";
let p=0,f=0;function t(n,fn){try{fn();p++;console.log(`PASS  ${n}`)}catch(e){f++;console.log(`FAIL  ${n}\n      ${e.message}`)}}
const families=["CF-01","CF-02","CF-03","CF-04","CF-05","CF-06"];
t("premium architecture uses exactly 12 stages",()=>assert.equal(STAGES.length,12));
t("premium architecture contains at least 24 meaningful decisions",()=>assert.ok(DECISION_ORDER.length>=24));
t("all 15 competency families remain represented",()=>{const used=new Set();for(const id of DECISION_ORDER){const d=DECISIONS[id];for(const c of (d.competencies||[d.competency]))used.add(c);}assert.equal(Object.keys(COMPETENCY_LABELS).length,15);for(let n=1;n<=15;n++)assert.ok(used.has(`M08-C${String(n).padStart(2,"0")}`));});
t("exactly six critical-failure families are explicitly mapped",()=>{const used=new Set(DECISION_ORDER.map(id=>DECISIONS[id].criticalFailureFamily).filter(Boolean));assert.deepEqual([...used].sort(),families);});
t("every critical family preserves a first-attempt trigger record",()=>{for(const cf of families){const id=DECISION_ORDER.find(x=>DECISIONS[x].criticalFailureFamily===cf);assert.ok(id,`${cf} has no decision`);const d=DECISIONS[id];assert.ok(d.criticalWrongResponse!==undefined,`${id} lacks a deterministic critical wrong response for gate testing`);let s=createInitialState();s=submitAttempt(s,id,d.criticalWrongResponse,1000);const r=s.decisions[id];assert.equal(r.criticalFailureOccurred,true,`${cf} did not trigger on first critical action`);assert.equal(r.criticalFailureFamily,cf);assert.equal(r.firstAttemptTimestamp,1000);}});
t("simple same-screen correction cannot resolve a critical failure",()=>{const id=DECISION_ORDER.find(x=>DECISIONS[x].criticalFailureFamily==="CF-02");const d=DECISIONS[id];let s=createInitialState();s=submitAttempt(s,id,d.criticalWrongResponse,1000);s=submitAttempt(s,id,d.correctKey??d.correctSet??d.correctMap,2000);assert.equal(s.decisions[id].criticalFailureResolved,false);assert.equal(computeCriticalFailureStatus(s)["CF-02"],"REASSESSMENT_REQUIRED");});
t("materially different reassessment can resolve a critical failure without erasing history",()=>{const id=DECISION_ORDER.find(x=>DECISIONS[x].criticalFailureFamily==="CF-02");const d=DECISIONS[id];let s=createInitialState();s=submitAttempt(s,id,d.criticalWrongResponse,1000);s={...s,decisions:{...s.decisions,[id]:{...s.decisions[id],criticalFailureResolved:true,reassessment:{scenarioId:"SIM08-R-CF02",materiallyDifferent:true,correct:true,timestamp:3000}}}};assert.equal(computeCriticalFailureStatus(s)["CF-02"],"RESOLVED_BY_REASSESSMENT");assert.equal(s.decisions[id].firstAttemptTimestamp,1000);});
t("completion record separates first-attempt and corrected performance",()=>{const record=computeCompletionRecord(createInitialState());assert.ok(Object.hasOwn(record,"firstAttemptScore"));assert.ok(Object.hasOwn(record,"finalScore"));assert.ok(Object.hasOwn(record,"competencies"));assert.ok(Object.hasOwn(record,"criticalFailures"));assert.ok(Object.hasOwn(record,"instructorReviewState"));});
t("successful final-state choices never use BOOKED",()=>{for(const id of DECISION_ORDER){const d=DECISIONS[id];if(d.finalStatusSuccess)assert.notEqual(d.finalStatusSuccess,"BOOKED");}});
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
